repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.6
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/rhysd/actionlint
  rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # v1.7.12
  hooks:
    - id: actionlint
- repo: https://github.com/woodruffw/zizmor-pre-commit
  rev: 9257c6050c0261b8c57e712f632dc4a8010109a9  # v1.25.2
  hooks:
    - id: zizmor