version: '3.9'

volumes:
  pg_data:

services:
  sqs:
    container_name: sqs
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      - 9325:9325

  api_db:
    container_name: api_db
    image: postgis/postgis:13-3.2-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  api_service:
    container_name: api_service
    build:
        context: .
        dockerfile: Dockerfile
    image: wcs/mermaid-api:latest
    volumes:
      - $PWD/src:/var/projects/webapp
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - api_db
      - sqs
