version: '3.9'

volumes:
  pg_data:

services:
  sqs:
    container_name: sqs
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      - 9325:9325

  api_db:
    container_name: api_db
    image: postgis/postgis:13-3.2-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 60s
      interval: 5s
      timeout: 3s
      retries: 10

  api_service:
    container_name: api_service
    build:
        context: .
        dockerfile: Dockerfile.ecs
    image: wcs/mermaid-api:latest
    volumes:
      - $PWD/src:/var/projects/webapp
    ports:
      - 8080:8080
    entrypoint: tail -f /dev/null
    env_file:
      - .env
      - .secrets.env
    depends_on:
      api_db:
        condition: service_healthy
      sqs:
        condition: service_started
