version: '2'

volumes:
  pg_data:

services:

  api_db:
    container_name: api_db
    image: mdillon/postgis:11-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  api_service:
    container_name: api_service
    build:
        context: .
        dockerfile: Dockerfile
    image: wcs/mermaid-api:latest
    volumes:
      - $PWD/src:/var/projects/webapp
    ports:
      - 8080:8080
    env_file:
      - .env

    links:
      - api_db
