from ..models import (
    BENTHICLIT_PROTOCOL,
    BENTHICPIT_PROTOCOL,
    FISHBELT_PROTOCOL,
    HABITATCOMPLEXITY_PROTOCOL,
    BLEACHINGQC_PROTOCOL,
    BENTHICPQT_PROTOCOL,
)

CSV_SCHEMAS = {
    BENTHICLIT_PROTOCOL: [
        "Site *",
        "Management *",
        "Sample date: Year *",
        "Sample date: Month *",
        "Sample date: Day *",
        "Sample time",
        "Depth *",
        "Transect length surveyed *",
        "Transect number *",
        "Transect label",
        "Reef slope",
        "Visibility",
        "Current",
        "Relative depth",
        "Tide",
        "Notes",
        "Observer emails *",
        "Benthic attribute *",
        "Growth form",
        "Observation length *",
    ],
    BENTHICPQT_PROTOCOL: [
        "Site *",
        "Management *",
        "Sample date: Year *",
        "Sample date: Month *",
        "Sample date: Day *",
        "Sample time",
        "Depth *",
        "Transect length surveyed *",
        "Number of quadrats *",
        "Quadrat size *",
        "Number of points per quadrat *",
        "Transect number *",
        "Transect label",
        "Reef slope",
        "Visibility",
        "Current",
        "Relative depth",
        "Tide",
        "Notes",
        "Observer emails *",
        "Quadrat *",
        "Benthic attribute *",
        "Growth form",
        "Number of points *",
    ],
    BENTHICPIT_PROTOCOL: [
        "Site *",
        "Management *",
        "Sample date: Year *",
        "Sample date: Month *",
        "Sample date: Day *",
        "Sample time",
        "Depth *",
        "Transect length surveyed *",
        "Interval size *",
        "Interval start *",
        "Transect number *",
        "Transect label",
        "Reef slope",
        "Visibility",
        "Current",
        "Relative depth",
        "Tide",
        "Notes",
        "Observer emails *",
        "Observation interval *",
        "Benthic attribute *",
        "Growth form",
    ],
    BLEACHINGQC_PROTOCOL: [
        "Site *",
        "Management *",
        "Sample date: Year *",
        "Sample date: Month *",
        "Sample date: Day *",
        "Sample time",
        "Depth *",
        "Quadrat size *",
        "Label",
        "Visibility",
        "Current",
        "Relative depth",
        "Tide",
        "Notes",
        "Observer emails *",
        "Benthic attribute",
        "Growth form",
        "Number of colonies normal",
        "Number of colonies pale",
        "Number of colonies bleached 0-20% bleached",
        "Number of colonies bleached 20-50% bleached",
        "Number of colonies bleached 50-80% bleached",
        "Number of colonies bleached 80-100% bleached",
        "Number of colonies recently dead",
        "Quadrat number",
        "Hard coral % cover",
        "Soft coral % cover",
        "Macroalgae % cover",
    ],
    HABITATCOMPLEXITY_PROTOCOL: [
        "Site *",
        "Management *",
        "Sample date: Year *",
        "Sample date: Month *",
        "Sample date: Day *",
        "Sample time",
        "Depth *",
        "Transect length surveyed *",
        "Interval size *",
        "Transect number *",
        "Transect label",
        "Reef slope",
        "Visibility",
        "Current",
        "Relative depth",
        "Tide",
        "Notes",
        "Observer emails *",
        "Observation interval *",
        "Habitat complexity score *",
    ],
    FISHBELT_PROTOCOL: [
        "Site *",
        "Management *",
        "Sample date: Year *",
        "Sample date: Month *",
        "Sample date: Day *",
        "Sample time",
        "Depth *",
        "Transect number *",
        "Transect label",
        "Transect length surveyed *",
        "Width *",
        "Fish size bin *",
        "Reef slope",
        "Visibility",
        "Current",
        "Relative depth",
        "Tide",
        "Notes",
        "Observer emails *",
        "Fish name *",
        "Size *",
        "Count *",
    ]
}