version: 2

default: &default
  docker:
    - image: cimg/python:3.8.5
      environment:
        PAGER: cat
  environment:
    AWS_DEFAULT_REGION: us-east-1

install_dependencies: &install_dependencies
  run:
    name: Load Dependencies
    command: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      pip install boto3==1.9.86 requests==2.20.1
      pip install git+https://github.com/data-mermaid/mermaid-changelog.git

build: &build
  run:
    name: Build
    command: ./ci_cd/build.sh ${CIRCLE_SHA1:0:7}

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8.5
        environment:
          PAGER: cat
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: echo "no test"

  deploy_dev:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker
      - *install_dependencies
      - *build
      - run:
          name: Docker image update
          command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag honeycrisp/mermaid-api:${CIRCLE_SHA1:0:7} honeycrisp/mermaid-api:mermaid-dev-api2
              docker push honeycrisp/mermaid-api:mermaid-dev-api2
      - run:
          name: Deploy
          command: |
              ./ci_cd/deploy.sh mermaid-dev-api2 ${CIRCLE_SHA1:0:7} Mermaid-API
              python ci_cd/wait_for_ok.py mermaid-dev-api2 ${CIRCLE_SHA1:0:7}
      - run:
          name: Update version
          command: |
              python ci_cd/update_version.py dev api "${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}"

  deploy_prod:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker
      - *install_dependencies
      - *build
      - run:
          name: Docker image update
          command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag honeycrisp/mermaid-api:${CIRCLE_SHA1:0:7} honeycrisp/mermaid-api:mermaid-prod-api2
              docker push honeycrisp/mermaid-api:mermaid-prod-api2
      - run:
          name: Deploy
          command: |
              ./ci_cd/deploy.sh mermaid-prod-api2 ${CIRCLE_SHA1:0:7} Mermaid-API
              python ci_cd/wait_for_ok.py mermaid-prod-api2 ${CIRCLE_SHA1:0:7}
      - run:
          name: Update version
          command: |
              python ci_cd/update_version.py prod api ${CIRCLE_TAG}
      - run:
          name: Update changelog
          command: |
              chlog

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context: org-global
          filters:
            tags:
              only: /.*/
      # branch: develop
      - deploy_dev:
          context: org-global
          filters:
            branches:
              only: dev
          requires:
            - build_and_test
      # tag: v1.2.3
      - deploy_prod:
          context: org-global
          filters:
            branches:
              ignore: /.*/  # IMPORTANT!
            tags:
              only: /v[0-9]+(\.[0-9]+)+/ # v1.2.3
          requires:
            - build_and_test
