# Generated by Django 3.2.18 on 2023-04-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("event", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "log_event",
            },
        ),
    ]
