# Generated by Django 3.2.20 on 2025-04-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0088_auto_20250318_1506"),
        ("tools", "0002_usermetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="MERMAIDFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "mermaid_feature",
                "verbose_name": "MERMAID Feature",
            },
        ),
        migrations.CreateModel(
            name="UserMERMAIDFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.mermaidfeature"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.profile"
                    ),
                ),
            ],
            options={
                "db_table": "user_mermaid_feature",
                "verbose_name": "User MERMAID Feature",
            },
        ),
    ]
