# Generated by Django 5.2.16 on 2026-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_mermaidfeature_usermermaidfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermetrics",
            name="project_tag_ids",
            field=models.TextField(blank=True, default=""),
        ),
    ]
