# Generated by Django 2.2.12 on 2021-04-15 21:52

from django.db import migrations, models

from api.models import revisions

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, editable=False, max_length=50)),
                ('record_id', models.UUIDField(db_index=True, editable=False)),
                ('project_id', models.UUIDField(db_index=True, editable=False, null=True)),
                ('profile_id', models.UUIDField(db_index=True, editable=False, null=True)),
                ('revision_num', models.IntegerField(default=1)),
                ('updated_on', models.DateTimeField(editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'db_table': 'revision',
                'unique_together': {('table_name', 'record_id')},
            },
        ),
        migrations.RunSQL(revisions.forward_sql, revisions.reverse_sql)
    ]
