# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 20:41
from __future__ import unicode_literals

from django.db import migrations

add_extension = "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
drop_extension = "DROP EXTENSION IF EXISTS pg_trgm;"

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(add_extension, drop_extension)
    ]
