# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190425_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishbelttransect',
            name='size_bin',
            # No actual null size_bins in production db
            field=models.ForeignKey(default='67c1356f-e0a7-4383-8034-77b2f36e1a49', on_delete=django.db.models.deletion.PROTECT, to='api.FishSizeBin'),
            preserve_default=False,
        ),
    ]
