# Generated by Django 3.2.14 on 2022-08-23 10:42

import rest_framework.utils.encoders
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_summarysampleeventmodel_sample_event_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarysampleeventmodel",
            name="id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="archivedrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="archivedrecord",
            name="record",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditrecord",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collectrecord",
            name="data",
            field=models.JSONField(
                blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="collectrecord",
            name="validations",
            field=models.JSONField(
                blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="covariate",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="covariate",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fishgroupingrelationship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="validations",
            field=models.JSONField(
                blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="obsbeltfish",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="obsbenthiclit",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="obsbenthicphotoquadrat",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="obsbenthicpit",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="obscoloniesbleached",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="obshabitatcomplexity",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="obsquadratbenthicpercent",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="revision",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sampleevent",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sampleevent",
            name="validations",
            field=models.JSONField(
                blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="validations",
            field=models.JSONField(
                blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="summarysampleeventmodel",
            name="project_admins",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="summarysampleeventmodel",
            name="protocols",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="summarysampleeventmodel",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uuidtaggeditem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
