# Generated by Django 3.2.15 on 2022-08-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220818_1823'),
        ('api', '0003_auto_20220823_1042'),
    ]

    operations = [
    ]
