# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190509_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authuser_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='belttransectwidth',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belttransectwidth_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='benthicattribute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benthicattribute_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='benthiclifehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benthiclifehistory_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='benthictransect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benthictransect_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='collectrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectrecord_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='current',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishattribute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishattribute_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishbelttransect_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishgroupfunction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishgroupfunction_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishgroupsize',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishgroupsize_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishgrouptrophic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishgrouptrophic_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishsize',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishsize_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='fishsizebin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishsizebin_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='growthform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growthform_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='habitatcomplexityscore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitatcomplexityscore_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='management',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='managementcompliance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managementcompliance_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='managementparty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managementparty_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpa_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='obsbeltfish',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsbeltfish_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='obsbenthiclit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsbenthiclit_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='obsbenthicpit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsbenthicpit_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='obscoloniesbleached',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obscoloniesbleached_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='observer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observer_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='obshabitatcomplexity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obshabitatcomplexity_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='obsquadratbenthicpercent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsquadratbenthicpercent_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectprofile_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadratcollection_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='reefexposure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reefexposure_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='reefslope',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reefslope_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='reeftype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reeftype_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='reefzone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reefzone_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='relativedepth',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relativedepth_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampleevent_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='tide',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tide_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='transectmethod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transectmethod_created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='visibility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_created_by', to='api.Profile'),
        ),
    ]
