# Generated by Django 2.2.12 on 2021-05-12 22:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210507_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='transectmethod',
            name='collect_record_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.IntegerField(choices=[(1, 'Submit Record'), (2, 'Edit Record')])),
                ('event_on', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=100)),
                ('record_id', models.UUIDField(db_index=True)),
                ('event_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
