# Generated by Django 3.2.15 on 2022-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221006_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarysampleeventmodel',
            name='data_policy_benthicpqt',
            field=models.CharField(default='public summary', max_length=50),
            preserve_default=False,
        ),
    ]
