# Generated by Django 2.2.12 on 2020-08-05 20:25

from django.db import migrations
from ..utils.sample_units import consolidate_sample_events
from ..models.view_models import model_view_migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20200717_1917")]

    operations = [
        migrations.RunPython(consolidate_sample_events, migrations.RunPython.noop),
        migrations.RunSQL(
            model_view_migrations.reverse_sql(), model_view_migrations.forward_sql()
        ),
        migrations.RunSQL(
            model_view_migrations.forward_sql(), model_view_migrations.reverse_sql()
        ),
    ]
