# Generated by Django 2.2.12 on 2020-08-05 20:25

from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension
from ..utils.sample_units import consolidate_sample_events
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20200717_1917")]

    operations = [
        CreateExtension("uuid-ossp"),
        migrations.CreateModel(
            name='SampleUnitCache',
            fields=[
                ('sample_unit_id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pseudosu_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('sample_event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'sample_unit_cache',
            },
        ),
        migrations.RunPython(consolidate_sample_events, migrations.RunPython.noop),
    ]
