# Generated by Django 3.2.15 on 2023-01-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_management_est_year'),
        ('api', '0006_summarysampleeventmodel_data_policy_benthicpqt'),
    ]

    operations = [
    ]
