# Generated by Django 3.2.15 on 2023-01-09 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_summarysampleeventmodel_data_policy_benthicpqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='est_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2023)], verbose_name='year established'),
        ),
    ]
