# Generated by Django 2.2.12 on 2021-08-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_obsbeltfish_size_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
