# Generated by Django 2.2.12 on 2020-08-19 21:30

from django.db import migrations
from ..models.view_models import model_view_migrations


populate_su_cache = """
INSERT INTO sample_unit_cache
WITH se_pseudosu_ids AS (
    SELECT
    uuid_generate_v4() AS pseudosu_id,
    array_agg(DISTINCT sample_unit_id) AS sample_unit_ids,
    sample_event_id
    FROM vw_beltfish_obs
    GROUP BY project_id, project_name, project_status, 
    project_notes, contact_link, tags, site_id, 
    site_name, location, site_notes, country_id, 
    country_name, reef_type, reef_zone, 
    reef_exposure, management_id, management_name, 
    management_name_secondary, management_est_year, management_size, 
    management_parties, management_compliance, management_rules, 
    management_notes, sample_event_id, sample_date, 
    sample_event_notes, depth, transect_number, 
    transect_len_surveyed, data_policy_beltfish
)
SELECT 
UNNEST(sample_unit_ids) AS sample_unit_id,
pseudosu_id,
sample_event_id
FROM se_pseudosu_ids;
"""

clear_su_cache = """
TRUNCATE sample_unit_cache;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200805_2025'),
    ]

    operations = [
        migrations.RunSQL(
            model_view_migrations.reverse_sql(), model_view_migrations.forward_sql()
        ),
        migrations.RunSQL(
            model_view_migrations.forward_sql(), model_view_migrations.reverse_sql()
        ),
        migrations.RunSQL(
            populate_su_cache, clear_su_cache
        ),
    ]
