# Generated by Django 2.2.12 on 2020-08-19 21:30

from django.db import migrations
from ..models.view_models import model_view_migrations, BeltFishSUView, BenthicLITSUView


populate_su_cache = """
INSERT INTO sample_unit_cache
WITH se_pseudosu_ids_bf AS (
    SELECT
    uuid_generate_v4() AS pseudosu_id,
    array_agg(DISTINCT sample_unit_id) AS sample_unit_ids,
    sample_event_id
    FROM vw_beltfish_obs
    GROUP BY {beltfish_fields}
)
SELECT 
UNNEST(sample_unit_ids) AS sample_unit_id,
pseudosu_id,
sample_event_id
FROM se_pseudosu_ids_bf;

INSERT INTO sample_unit_cache
WITH se_pseudosu_ids_bl AS (
    SELECT
    uuid_generate_v4() AS pseudosu_id,
    array_agg(DISTINCT sample_unit_id) AS sample_unit_ids,
    sample_event_id
    FROM vw_benthiclit_obs
    GROUP BY {benthiclit_fields}
)
SELECT 
UNNEST(sample_unit_ids) AS sample_unit_id,
pseudosu_id,
sample_event_id
FROM se_pseudosu_ids_bl
ON CONFLICT DO NOTHING;
""".format(
    beltfish_fields=", ".join(BeltFishSUView.su_fields),
    benthiclit_fields=", ".join(BenthicLITSUView.su_fields),
)

clear_su_cache = """
TRUNCATE sample_unit_cache;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200805_2025'),
    ]

    operations = [
        migrations.RunSQL(
            model_view_migrations.reverse_sql(), model_view_migrations.forward_sql()
        ),
        migrations.RunSQL(
            model_view_migrations.forward_sql(), model_view_migrations.reverse_sql()
        ),
        migrations.RunSQL(
            populate_su_cache, clear_su_cache
        ),
    ]
