# Generated by Django 2.2.12 on 2021-08-12 20:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covariate',
            name='name',
            field=models.CharField(choices=[('aca_benthic', 'aca_benthic'), ('aca_geomorphic', 'aca_geomorphic'), ('vot_score', 'vot_score'), ('vot_scorecn', 'vot_scorecn'), ('vot_scorecy', 'vot_scorecy'), ('vot_scorepfc', 'vot_scorepfc'), ('vot_scoreth', 'vot_scoreth'), ('vot_scoretr', 'vot_scoretr'), ('vot_grav_nc', 'vot_grav_nc'), ('vot_sediment', 'vot_sediment'), ('vot_nutrient', 'vot_nutrient'), ('vot_pop_count', 'vot_pop_count'), ('vot_num_ports', 'vot_num_ports'), ('vot_reef_value', 'vot_reef_value'), ('vot_cumul_score', 'vot_cumul_score')], max_length=100),
        ),
        migrations.AlterField(
            model_name='covariate',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
