# Generated by Django 2.2.12 on 2020-09-08 20:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200819_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarySiteViewModel',
            fields=[
                ('site_id', models.UUIDField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('site_notes', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('project_id', models.UUIDField()),
                ('project_name', models.CharField(max_length=255)),
                ('project_status', models.PositiveSmallIntegerField(choices=[(90, 'open'), (80, 'test'), (10, 'locked')], default=90)),
                ('project_notes', models.TextField(blank=True)),
                ('contact_link', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('country_id', models.UUIDField()),
                ('country_name', models.CharField(max_length=50)),
                ('reef_type', models.CharField(max_length=50)),
                ('reef_zone', models.CharField(max_length=50)),
                ('reef_exposure', models.CharField(max_length=50)),
                ('project_admins', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_min', models.DateField(blank=True, null=True)),
                ('date_max', models.DateField(blank=True, null=True)),
                ('depth_avg_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('depth_avg_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('management_regimes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('protocols', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data_policy_beltfish', models.CharField(max_length=50)),
                ('data_policy_benthiclit', models.CharField(max_length=50)),
                ('data_policy_benthicpit', models.CharField(max_length=50)),
                ('data_policy_habitatcomplexity', models.CharField(max_length=50)),
                ('data_policy_bleachingqc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_summary_site',
                'managed': False,
            },
        ),
    ]
