# Generated by Django 2.2.3 on 2019-10-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190912_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obsbeltfish',
            options={'ordering': ['created_on'], 'verbose_name': 'fish belt transect observation'},
        ),
        migrations.AlterModelOptions(
            name='obsbenthiclit',
            options={'ordering': ['created_on'], 'verbose_name': 'benthic LIT observation'},
        ),
        migrations.AlterModelOptions(
            name='obsbenthicpit',
            options={'ordering': ['interval'], 'verbose_name': 'benthic PIT observation'},
        ),
        migrations.AlterModelOptions(
            name='obscoloniesbleached',
            options={'ordering': ['created_on'], 'verbose_name': 'bleaching quadrat collection colonies bleached observation'},
        ),
        migrations.AlterModelOptions(
            name='obshabitatcomplexity',
            options={'ordering': ['interval'], 'verbose_name': 'habitat complexity transect observation'},
        ),
        migrations.AlterModelOptions(
            name='obsquadratbenthicpercent',
            options={'ordering': ['created_on'], 'verbose_name': 'bleaching quadrat collection percent benthic cover observation'},
        ),
    ]
