# Generated by Django 2.2.12 on 2020-09-18 14:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_summarysiteviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
