# Generated by Django 2.2.12 on 2021-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210812_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleevent',
            name='current',
        ),
        migrations.RemoveField(
            model_name='sampleevent',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='sampleevent',
            name='relative_depth',
        ),
        migrations.RemoveField(
            model_name='sampleevent',
            name='sample_time',
        ),
        migrations.RemoveField(
            model_name='sampleevent',
            name='tide',
        ),
        migrations.RemoveField(
            model_name='sampleevent',
            name='visibility',
        ),
    ]
