# Generated by Django 2.2.12 on 2020-10-20 20:31

from django.db import migrations
from ..models.view_models import (
    model_view_migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_summarysiteviewmodel'),
    ]

    operations = [
        migrations.RunSQL(
            model_view_migrations.reverse_sql(), model_view_migrations.forward_sql() 
        ),
    ]
