# Generated by Django 2.2.3 on 2019-11-13 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


def set_belttransectwidth_name(apps, schema_editor):
    BeltTransectWidth = apps.get_model("api", "BeltTransectWidth")
    if hasattr(BeltTransectWidth, "val") is False:
        return

    for btw in BeltTransectWidth.objects.all():
        if btw.name:
            continue
        btw.name = "{}m".format(getattr(btw, "val"))
        btw.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0008_auto_20191022_0555")]

    operations = [
        migrations.AddField(
            model_name="belttransectwidth",
            name="name",
            field=models.CharField(max_length=100, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="belttransectwidth",
            name="val",
            field=models.PositiveSmallIntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_belttransectwidth_name, migrations.RunPython.noop),
        migrations.CreateModel(
            name="BeltTransectWidthCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("==", "=="),
                            ("!=", "!="),
                            ("<", "<"),
                            ("<=", "<="),
                            (">", ">"),
                            (">=", ">="),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="fish length (cm)",
                    ),
                ),
                ("val", models.PositiveSmallIntegerField()),
                (
                    "belttransectwidth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conditions",
                        to="api.BeltTransectWidth",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="belttransectwidthcondition_created_by",
                        to="api.Profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="belttransectwidthcondition_updated_by",
                        to="api.Profile",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterUniqueTogether(
            name='belttransectwidthcondition',
            unique_together={('belttransectwidth', 'operator', 'size')},
        ),
    ]
