# Generated by Django 2.2.3 on 2019-11-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191112_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='gear_restriction',
            field=models.BooleanField(default=False, verbose_name='partial gear restriction'),
        ),
        migrations.AlterField(
            model_name='management',
            name='no_take',
            field=models.BooleanField(default=False, verbose_name='no-take zone'),
        ),
        migrations.AlterField(
            model_name='management',
            name='open_access',
            field=models.BooleanField(default=False, verbose_name='open access'),
        ),
        migrations.AlterField(
            model_name='management',
            name='periodic_closure',
            field=models.BooleanField(default=False, verbose_name='periodic closure'),
        ),
        migrations.AlterField(
            model_name='management',
            name='size_limits',
            field=models.BooleanField(default=False, verbose_name='size limits'),
        ),
        migrations.AlterField(
            model_name='management',
            name='species_restriction',
            field=models.BooleanField(default=False, verbose_name='partial species restriction'),
        ),
    ]
