# Generated by Django 2.2.12 on 2020-10-20 22:17

from django.db import migrations
from ..models.view_models import (
    model_view_migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201020_2031'),
    ]

    operations = [
        migrations.RunSQL(
            model_view_migrations.reverse_sql(), model_view_migrations.forward_sql()
        ),
        migrations.RunSQL(
            model_view_migrations.forward_sql(), model_view_migrations.reverse_sql()
        ),
    ]
