# Generated by Django 3.2.17 on 2023-02-14 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_auto_20230214_2208"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppVersion",
        ),
    ]
