# Generated by Django 2.2.24 on 2021-08-24 12:58

from django.db import migrations
from api.models import SummarySiteViewModel


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210818_1353'),
    ]

    operations = [
        migrations.RunSQL(SummarySiteViewModel.reverse_sql, migrations.RunSQL.noop),
        migrations.RunSQL(SummarySiteViewModel.sql, SummarySiteViewModel.reverse_sql)
    ]
