# Generated by Django 2.2.24 on 2021-08-24 12:58

from django.db import migrations


drop_vw_summary_site = "DROP MATERIALIZED VIEW IF EXISTS vw_summary_site;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210818_1353'),
    ]

    operations = [
        migrations.RunSQL(drop_vw_summary_site, drop_vw_summary_site),
    ]
