# Generated by Django 3.2.17 on 2023-02-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_delete_appversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="current_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="label",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="relative_depth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="sample_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="tide_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="visibility_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="current_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="label",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="relative_depth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="sample_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="tide_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="visibility_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="current_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="label",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="relative_depth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="sample_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="tide_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="visibility_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="current_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="label",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="relative_depth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="sample_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="tide_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="visibility_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="current_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="label",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="relative_depth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="sample_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="tide_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="visibility_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="current_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="label",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="relative_depth",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="sample_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="tide_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="visibility_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
