# Generated by Django 2.2.6 on 2020-02-13 18:07

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
from django.contrib.gis.geos import GEOSGeometry


class Migration(migrations.Migration):

    dependencies = [("api", "0010_auto_20191112_1919")]

    operations = [
        migrations.AddField(
            model_name="region",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                default=GEOSGeometry("MULTIPOLYGON(((0 0,0 0,0 0,0 0,0 0)))"),
                geography=True,
                srid=4326,
            ),
            preserve_default=False,
        ),
    ]
