# Generated by Django 2.2.12 on 2021-04-07 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210329_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRevision',
            fields=[
                ('rev_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('profile_id', models.UUIDField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'record_revision',
            },
        ),
        migrations.CreateModel(
            name='TableRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_rev_id', models.UUIDField(db_index=True)),
                ('table_name', models.CharField(db_index=True, max_length=50)),
                ('updated_on', models.DateTimeField()),
                ('project_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'table_revision',
            },
        ),
    ]
