# Generated by Django 2.2.6 on 2020-02-08 05:56

from django.db import migrations


region_names = [
    "Arctic",
    "Central Indo-Pacific",
    "Eastern Indo-Pacific",
    "Southern Ocean",
    "Temperate Australasia",
    "Temperate Northern Atlantic",
    "Temperate Northern Pacific",
    "Temperate South America",
    "Temperate Southern Africa",
    "Tropical Atlantic",
    "Tropical Eastern Pacific",
    "Western Indo-Pacific",
]


def load_regions(apps, *args, **kwargs):
    Region = apps.get_model("api", "Region")
    for region_name in region_names:
        Region.objects.get_or_create(name=region_name)


def unload_regions(apps, *args, **kwargs):
    Region = apps.get_model("api", "Region")
    Region.objects.filter(name__in=region_names).delete()


class Migration(migrations.Migration):

    dependencies = [("api", "0010_auto_20191112_1919")]

    operations = [migrations.RunPython(load_regions, unload_regions)]
