# Generated by Django 2.2.24 on 2021-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210824_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covariate',
            name='display',
        ),
        migrations.AlterField(
            model_name='covariate',
            name='name',
            field=models.CharField(choices=[('aca_benthic', 'Benthic_Allen Coral Atlas'), ('aca_geomorphic', 'Geomorphic_Allen Coral Atlas'), ('beyer_score', '50 Reefs score_Beyer'), ('beyer_scorecn', '50 Reefs connectivity_Beyer'), ('beyer_scorecy', '50 Reefs cyclones_Beyer'), ('beyer_scorepfc', '50 Reefs thermal future_Beyer'), ('beyer_scoreth', '50 Reefs thermal history_Beyer'), ('beyer_scoretr', '50 Reefs thermal recent_Beyer'), ('andrello_grav_nc', 'Market gravity_Andrello'), ('andrello_sediment', 'Sediment_Andrello'), ('andrello_nutrient', 'Nutrient_Andrello'), ('andrello_pop_count', 'Human population_Andrello'), ('andrello_num_ports', 'Number of ports_Andrello'), ('andrello_reef_value', 'Tourism value_Andrello'), ('andrello_cumul_score', 'Cumulative local pressure_Andrello')], max_length=100),
        ),
    ]
