# Generated by Django 2.2.12 on 2021-01-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200903_2034'),
        ('api', '0010_auto_20200921_1527'),
    ]

    operations = [
    ]
