# Generated by Django 2.2.9 on 2020-02-05 22:48

from django.db import migrations
from ..models.view_models import BeltFishObsView, BeltFishSUView, BeltFishSEView

drop_obs_view = "DROP VIEW IF EXISTS public.vw_beltfish_obs;"
drop_su_view = "DROP VIEW IF EXISTS public.vw_beltfish_su;"
drop_se_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200205_1929'),
    ]

    operations = [
        migrations.RunSQL(BeltFishObsView.sql, drop_obs_view),
        migrations.RunSQL(BeltFishSUView.sql, drop_su_view),
        migrations.RunSQL(BeltFishSEView.sql, drop_se_view),
    ]
