# Generated by Django 2.2.12 on 2021-04-07 19:10

from django.db import migrations
from api.models import revisions


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_recordrevision_tablerevision"),
    ]

    operations = [migrations.RunSQL(revisions.forward_sql, revisions.reverse_sql)]
