# Generated by Django 2.2.12 on 2020-12-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201214_2207'),
    ]

    operations = [
    ]
