# Generated by Django 2.2.24 on 2021-11-08 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211108_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benthictransect',
            name='depth',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
        ),
        migrations.AlterField(
            model_name='fishbelttransect',
            name='depth',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
        ),
        migrations.AlterField(
            model_name='quadratcollection',
            name='depth',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
            preserve_default=False,
        ),
    ]
