# Generated by Django 2.2.9 on 2020-02-06 00:51

from django.db import migrations
from ..models.view_models import BeltFishSUView

drop_view = "DROP VIEW IF EXISTS public.vw_beltfish_su;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200205_2248'),
    ]

    operations = [
        migrations.RunSQL(BeltFishSUView.sql, drop_view)
    ]
