# Generated by Django 2.2.6 on 2020-02-11 16:05

from django.db import migrations


def update_functional_groups(apps, *args, **kwargs):
    # A - planktivore
    # D - phytoplanktivore
    # D - zooplanktivore
    FishSpecies = apps.get_model("api", "FishSpecies")
    FishGroupFunction = apps.get_model("api", "FishGroupFunction")

    func_group, _ = FishGroupFunction.objects.get_or_create(name="planktivore")
    FishSpecies.objects.filter(
        functional_group__name__in=["phytoplanktivore", "zooplanktivore"]
    ).update(functional_group=func_group)

    FishGroupFunction.objects.filter(
        name__in=["phytoplanktivore", "zooplanktivore"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [("api", "0012_auto_20200211_0428")]

    operations = [
        migrations.RunPython(update_functional_groups, migrations.RunPython.noop)
    ]
