# Generated by Django 3.2.17 on 2023-03-22 23:11

from django.db import migrations

from api.models.revisions import forward_sql


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230322_1451'),
    ]

    operations = [
        migrations.RunSQL(forward_sql),
    ]
