# Generated by Django 2.2.9 on 2020-02-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200121_2119'),
        ('api', '0013_auto_20200213_1808'),
    ]

    operations = [
    ]
