# Generated by Django 2.2.9 on 2020-03-10 07:39

from django.db import migrations
from ..models.view_models import BeltFishSEView

drop_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200206_0051'),
    ]

    operations = [
        migrations.RunSQL(BeltFishSEView.sql, drop_view)
    ]
