# Generated by Django 3.2.18 on 2023-03-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230316_1608'),
        ('api', '0014_auto_20230322_2311'),
    ]

    operations = [
    ]
