# Generated by Django 2.2.24 on 2022-01-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211220_1909'),
        ('api', '0015_summarysampleeventmodel_summarysampleeventsqlmodel'),
    ]

    operations = [
    ]
