# Generated by Django 3.2.18 on 2023-04-05 12:18

from django.db import migrations

from api.models.revisions import forward_sql


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_merge_0013_auto_20230316_1608_0014_auto_20230322_2311"),
    ]

    operations = [
        migrations.RunSQL(forward_sql, ""),
    ]
