# Generated by Django 2.2.9 on 2020-03-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015__auto_20200218_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='benthicpit',
            name='interval_start',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='interval start (m)'),
        ),
    ]
