# Generated by Django 2.2.12 on 2021-01-30 16:18

from django.db import migrations
from ..models.view_models import (
    model_view_migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210130_1617'),
    ]

    operations = [
        migrations.RunSQL(
            model_view_migrations.reverse_sql(), model_view_migrations.forward_sql()
        ),
        migrations.RunSQL(
            model_view_migrations.forward_sql(), model_view_migrations.reverse_sql()
        ),
    ]
