# Generated by Django 2.2.9 on 2020-03-11 05:30

from django.db import migrations, models


def set_interval_start_for_existing(apps, schema_editor):
    BenthicPIT = apps.get_model('api', 'BenthicPIT')
    for b in BenthicPIT.objects.all():
        b.interval_start = b.interval_size
        b.save()


def reverse_interval_start_for_existing(apps, schema_editor):
    BenthicPIT = apps.get_model('api', 'BenthicPIT')
    for b in BenthicPIT.objects.all():
        b.interval_start = 0.5
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015__auto_20200218_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='benthicpit',
            name='interval_start',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='interval start (m)'),
        ),
        migrations.RunPython(set_interval_start_for_existing, reverse_interval_start_for_existing)
    ]
