# Generated by Django 2.2.24 on 2022-01-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20220114_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_pk', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'edited_projects',
            },
        ),
    ]
