# Generated by Django 2.2.24 on 2022-01-25 16:54

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20220114_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadratTransect',
            fields=[
                ('benthictransect_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BenthicTransect')),
                ('quadrat_size', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='single quadrat area (m2)')),
                ('num_quadrats', models.PositiveSmallIntegerField()),
                ('num_points_per_quadrat', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'transect',
                'ordering': ('sample_event',),
                'abstract': False,
            },
            bases=('api.benthictransect',),
        ),
        migrations.CreateModel(
            name='BenthicPhotoQuadratTransect',
            fields=[
                ('transectmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.TransectMethod')),
                ('quadrat_transect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benthic_photo_quadrat_transect_method', to='api.QuadratTransect', verbose_name='benthic photo quadrat transect')),
            ],
            options={
                'verbose_name': 'benthic photo quadrat transect',
                'verbose_name_plural': 'benthic photo quadrat transects',
                'db_table': 'transectmethod_benthicpqt',
            },
            bases=('api.transectmethod',),
        ),
        migrations.CreateModel(
            name='ObsBenthicPhotoQuadrat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('quadrat_number', models.PositiveSmallIntegerField(verbose_name='quadrat number')),
                ('num_points', models.PositiveSmallIntegerField(default=0, verbose_name='number of points')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.BenthicAttribute')),
                ('benthic_photo_quadrat_transect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BenthicPhotoQuadratTransect')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsbenthicphotoquadrat_created_by', to='api.Profile')),
                ('growth_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GrowthForm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsbenthicphotoquadrat_updated_by', to='api.Profile')),
            ],
            options={
                'verbose_name': 'benthic photo quadrat transect observation',
                'db_table': 'obs_benthic_photo_quadrat',
                'ordering': ['created_on'],
                'unique_together': {('benthic_photo_quadrat_transect', 'quadrat_number', 'attribute', 'growth_form')},
            },
        ),
    ]
