# Generated by Django 2.2.9 on 2020-03-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200206_0051'),
        ('api', '0016_benthicpit_interval_start'),
    ]

    operations = [
    ]
