# Generated by Django 2.2.24 on 2022-01-20 20:48

from django.db import migrations


drop_vw_summary_site = "DROP MATERIALIZED VIEW IF EXISTS vw_summary_site;"

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20220114_1501'),
    ]

    operations = [
        migrations.RunSQL(drop_vw_summary_site, drop_vw_summary_site),
    ]
