# Generated by Django 2.2.9 on 2020-03-11 21:22

from django.db import migrations, models
from ..models.view_models import BeltFishObsView, BeltFishSUView, BeltFishSEView

drop_obs_view = "DROP VIEW IF EXISTS public.vw_beltfish_obs CASCADE;"
drop_su_view = "DROP VIEW IF EXISTS public.vw_beltfish_su;"
drop_se_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20200311_1934'),
    ]

    operations = [
        migrations.RunSQL(drop_obs_view, BeltFishObsView.sql),
        migrations.AlterField(
            model_name='fishsizebin',
            name='val',
            field=models.CharField(max_length=100),
        ),
        migrations.RunSQL(BeltFishObsView.sql, drop_obs_view),
        migrations.RunSQL(BeltFishSUView.sql, drop_su_view),
        migrations.RunSQL(BeltFishSEView.sql, drop_se_view),
    ]
