# Generated by Django 2.2.24 on 2022-01-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220120_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsquadratbenthicpercent',
            name='percent_algae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='macroalgae, % cover'),
        ),
        migrations.AlterField(
            model_name='obsquadratbenthicpercent',
            name='percent_hard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='hard coral, % cover'),
        ),
        migrations.AlterField(
            model_name='obsquadratbenthicpercent',
            name='percent_soft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='soft coral, % cover'),
        ),
    ]
