# Generated by Django 2.2.24 on 2022-02-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220125_1654'),
        ('api', '0018_auto_20220120_2049'),
    ]

    operations = [
    ]
