# Generated by Django 2.2.9 on 2020-03-25 18:54

from django.db import migrations
from ..models.view_models import BeltFishObsView, BeltFishSUView, BeltFishSEView

drop_obs_view = "DROP VIEW IF EXISTS public.vw_beltfish_obs CASCADE;"
drop_su_view = "DROP VIEW IF EXISTS public.vw_beltfish_su;"
drop_se_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200325_1744'),
    ]

    operations = [
        migrations.RunSQL(drop_obs_view, BeltFishObsView.sql),
        migrations.RunSQL(BeltFishObsView.sql, drop_obs_view),
        migrations.RunSQL(BeltFishSUView.sql, drop_su_view),
        migrations.RunSQL(BeltFishSEView.sql, drop_se_view),
    ]
