# Generated by Django 2.2.9 on 2020-03-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200311_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sampleevent',
            unique_together=set(),
        ),
    ]
