# Generated by Django 3.2.18 on 2023-04-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230425_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={'ordering': ('val', 'name')},
        ),
        migrations.AlterModelOptions(
            name='tide',
            options={'ordering': ('val', 'name')},
        ),
    ]
