# Generated by Django 2.2.27 on 2022-02-16 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20220208_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='est_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='year established'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='est_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='year established'),
        ),
    ]
