# Generated by Django 2.2.27 on 2022-05-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220216_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quadrattransect',
            options={},
        ),
        migrations.AlterModelTable(
            name='quadrattransect',
            table='quadrat_transect',
        ),
    ]
