# Generated by Django 2.2.9 on 2020-04-07 20:00

from django.db import migrations
from ..models.view_models import (
    SampleEventViewModel,
    BeltFishObsView,
    BeltFishSUView,
    BeltFishSEView,
    BenthicPITObsView,
    BenthicPITSUView,
    BenthicPITSEView,
)

drop_se_view = "DROP VIEW IF EXISTS public.vw_sample_events;"
drop_fb_obs_view = "DROP VIEW IF EXISTS public.vw_beltfish_obs CASCADE;"
drop_fb_su_view = "DROP VIEW IF EXISTS public.vw_beltfish_su;"
drop_fb_se_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"
drop_bp_obs_view = "DROP VIEW IF EXISTS public.vw_benthicpit_obs;"
drop_bp_su_view = "DROP VIEW IF EXISTS public.vw_benthicpit_su;"
drop_bp_se_view = "DROP VIEW IF EXISTS public.vw_benthicpit_se;"


class Migration(migrations.Migration):

    dependencies = [("api", "0020_auto_20200401_0707")]

    operations = [
        migrations.RunSQL(SampleEventViewModel.sql, drop_se_view),
        migrations.RunSQL(drop_fb_obs_view, BeltFishObsView.sql),
        migrations.RunSQL(BeltFishObsView.sql, drop_fb_obs_view),
        migrations.RunSQL(BeltFishSUView.sql, drop_fb_su_view),
        migrations.RunSQL(BeltFishSEView.sql, drop_fb_se_view),
        migrations.RunSQL(BenthicPITObsView.sql, drop_bp_obs_view),
        migrations.RunSQL(BenthicPITSUView.sql, drop_bp_su_view),
        migrations.RunSQL(BenthicPITSEView.sql, drop_bp_se_view),
    ]
