# Generated by Django 3.2.18 on 2023-08-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_auto_20230529_1755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltfishobsmodel",
            name="observation_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
