# Generated by Django 2.2.27 on 2022-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220505_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsbenthicphotoquadrat',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='data_policy_benthicpqt',
            field=models.PositiveSmallIntegerField(choices=[(10, 'private'), (50, 'public summary'), (100, 'public')], default=50),
        ),
    ]
