# Generated by Django 3.2.18 on 2023-08-03 17:02
from api.utils.q import submit_job
from api.utils.summary_cache import update_summary_cache
from django.db import migrations


def update_cache(apps, schema_editor):
    Project = apps.get_model("api", "Project")
    for project in Project.objects.all():
        print(f"project {project.pk}")
        submit_job(5, update_summary_cache, project_id=project.pk, skip_test_project=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_beltfishobsmodel_observation_notes'),
    ]

    operations = [
        migrations.RunPython(update_cache, migrations.RunPython.noop)
    ]
