# Generated by Django 2.2.9 on 2020-04-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200407_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishgrouping',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='fishfamily',
            name='grouping',
        ),
        migrations.AlterModelTable(
            name='fishgrouping',
            table='fish_grouping',
        ),
        migrations.CreateModel(
            name='FishGroupingRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouping_attribute', to='api.FishAttribute')),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_grouping', to='api.FishGrouping')),
            ],
        ),
    ]
