# Generated by Django 2.2.9 on 2020-04-16 19:32

from django.db import migrations, models
from ..models.view_models import (
    FishAttributeView,
    BeltFishObsView,
    BeltFishSUView,
    BeltFishSEView,
)

drop_fa_view = "DROP VIEW IF EXISTS public.vw_fish_attributes CASCADE;"
drop_fb_obs_view = "DROP VIEW IF EXISTS public.vw_beltfish_obs CASCADE;"
drop_fb_su_view = "DROP VIEW IF EXISTS public.vw_beltfish_su CASCADE;"
drop_fb_se_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200407_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishgrouping',
            name='regions',
            field=models.ManyToManyField(blank=True, to='api.Region'),
        ),
        migrations.RunSQL(drop_fa_view, FishAttributeView.sql),
        migrations.RunSQL(FishAttributeView.sql, drop_fa_view),
        migrations.RunSQL(BeltFishObsView.sql, drop_fb_obs_view),
        migrations.RunSQL(BeltFishSUView.sql, drop_fb_su_view),
        migrations.RunSQL(BeltFishSEView.sql, drop_fb_se_view),
    ]
