# Generated by Django 2.2.9 on 2020-04-09 21:48

from django.db import migrations
from ..models.view_models import *

drop_fa_view = "DROP VIEW IF EXISTS public.vw_fish_attributes CASCADE;"
drop_fb_obs_view = "DROP VIEW IF EXISTS public.vw_beltfish_obs;"
drop_fb_su_view = "DROP VIEW IF EXISTS public.vw_beltfish_su;"
drop_fb_se_view = "DROP VIEW IF EXISTS public.vw_beltfish_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200407_2226'),
    ]

    operations = [
        migrations.RunSQL(drop_fa_view, FishAttributeView.sql),
        migrations.RunSQL(FishAttributeView.sql, drop_fa_view),
        migrations.RunSQL(BeltFishObsView.sql, drop_fb_obs_view),
        migrations.RunSQL(BeltFishSUView.sql, drop_fb_su_view),
        migrations.RunSQL(BeltFishSEView.sql, drop_fb_se_view),
    ]
