# Generated by Django 3.2.20 on 2023-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_benthicphotoquadrattransectsumodel_num_points_nonother'),
    ]

    operations = [
        migrations.AddField(
            model_name='beltfishsemodel',
            name='depth_sd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='depth standard deviation (m)'),
        ),
        migrations.AddField(
            model_name='benthiclitsemodel',
            name='depth_sd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='depth standard deviation (m)'),
        ),
        migrations.AddField(
            model_name='benthicphotoquadrattransectsemodel',
            name='depth_sd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='depth standard deviation (m)'),
        ),
        migrations.AddField(
            model_name='benthicpitsemodel',
            name='depth_sd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='depth standard deviation (m)'),
        ),
        migrations.AddField(
            model_name='bleachingqcsemodel',
            name='depth_sd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='depth standard deviation (m)'),
        ),
        migrations.AddField(
            model_name='habitatcomplexitysemodel',
            name='depth_sd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='depth standard deviation (m)'),
        ),
        migrations.AlterField(
            model_name='beltfishsemodel',
            name='depth_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='depth mean (m)'),
        ),
        migrations.AlterField(
            model_name='benthiclitsemodel',
            name='depth_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='depth mean (m)'),
        ),
        migrations.AlterField(
            model_name='benthicphotoquadrattransectsemodel',
            name='depth_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='depth mean (m)'),
        ),
        migrations.AlterField(
            model_name='benthicpitsemodel',
            name='depth_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='depth mean (m)'),
        ),
        migrations.AlterField(
            model_name='bleachingqcsemodel',
            name='depth_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='depth mean (m)'),
        ),
        migrations.AlterField(
            model_name='habitatcomplexitysemodel',
            name='depth_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='depth mean (m)'),
        ),
    ]
