# Generated by Django 2.2.27 on 2022-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrattransect',
            name='quadrat_number_start',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of first quadrat'),
        ),
    ]
