# Generated by Django 2.2.27 on 2022-06-28 13:13

from django.db import connection
from django.db import migrations


forward_sql = """

DELETE FROM public.transectmethod_benthicpqt;
DELETE FROM public.quadrat_transect;

ALTER TABLE public.transectmethod_benthicpqt DROP COLUMN quadrat_transect_id;
ALTER TABLE public.quadrat_transect DROP COLUMN benthictransect_ptr_id;

ALTER TABLE public.quadrat_transect ADD COLUMN id uuid NOT NULL PRIMARY KEY;
ALTER TABLE public.quadrat_transect ADD COLUMN created_on timestamp with time zone NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN updated_on timestamp with time zone NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN notes text COLLATE pg_catalog."default" NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN len_surveyed numeric(4,1) NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN "number" smallint NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN sample_event_id uuid NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN updated_by_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN reef_slope_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN label character varying(50) COLLATE pg_catalog."default" NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN created_by_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN collect_record_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN current_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN depth numeric(3,1) NOT NULL;
ALTER TABLE public.quadrat_transect ADD COLUMN relative_depth_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN sample_time time without time zone;
ALTER TABLE public.quadrat_transect ADD COLUMN tide_id uuid;
ALTER TABLE public.quadrat_transect ADD COLUMN visibility_id uuid;

ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_created_by_id_5cbe9ac2_fk_profile_id FOREIGN KEY (created_by_id)
    REFERENCES public.profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_current_id_fd3e44ba_fk_api_current_id FOREIGN KEY (current_id)
    REFERENCES public.api_current (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_number_3a255e75_check CHECK (number >= 0);


ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_reef_slope_id_fdce2f56_fk_api_reefslope_id FOREIGN KEY (reef_slope_id)
    REFERENCES public.api_reefslope (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_relative_depth_id_5186c0d2_fk_api_relat FOREIGN KEY (relative_depth_id)
    REFERENCES public.api_relativedepth (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_sample_event_id_374948bd_fk_sample_event_id FOREIGN KEY (sample_event_id)
    REFERENCES public.sample_event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_tide_id_9f7e0d27_fk_api_tide_id FOREIGN KEY (tide_id)
    REFERENCES public.api_tide (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_updated_by_id_e165f54f_fk_profile_id FOREIGN KEY (updated_by_id)
    REFERENCES public.profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE IF EXISTS public.quadrat_transect
    ADD CONSTRAINT quadrat_transect_visibility_id_c806fe0c_fk_api_visibility_id FOREIGN KEY (visibility_id)
    REFERENCES public.api_visibility (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;


CREATE INDEX IF NOT EXISTS quadrat_transect_created_by_id_5cbe9ac6
    ON public.quadrat_transect USING btree
    (created_by_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_current_id_fd3e44ba
    ON public.quadrat_transect USING btree
    (current_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_reef_slope_id_fdce2f56
    ON public.quadrat_transect USING btree
    (reef_slope_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_relative_depth_id_5186c0d2
    ON public.quadrat_transect USING btree
    (relative_depth_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_sample_event_id_374948bd
    ON public.quadrat_transect USING btree
    (sample_event_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_tide_id_9f7e0d27
    ON public.quadrat_transect USING btree
    (tide_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_updated_by_id_e165f54f
    ON public.quadrat_transect USING btree
    (updated_by_id ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE INDEX IF NOT EXISTS quadrat_transect_visibility_id_c806fe0c
    ON public.quadrat_transect USING btree
    (visibility_id ASC NULLS LAST)
    TABLESPACE pg_default;


ALTER TABLE IF EXISTS public.transectmethod_benthicpqt
    ADD COLUMN IF NOT EXISTS quadrat_transect_id uuid NOT NULL;

ALTER TABLE IF EXISTS public.transectmethod_benthicpqt
    ADD CONSTRAINT transectmethod_benth_quadrat_transect_id_47985aa6_fk_transect_ FOREIGN KEY (quadrat_transect_id)
    REFERENCES public.quadrat_transect (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;

"""

def forward(apps, schema_editor):
    with connection.cursor() as cur:
        # Check if migration already applied
        column_check = """
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name='quadrat_transect' and column_name='id';
        """
        cur.execute(column_check)
        if cur.rowcount == 1:
            print("Quadtrat transect migration already applied")
            return
        
        cur.execute(forward_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_quadrattransect_quadrat_number_start'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
