# Generated by Django 3.2.20 on 2023-10-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_beltfishobsmodel_assigned_transect_width_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beltfishsemodel',
            old_name='biomass_kgha_by_fish_family_avg',
            new_name='biomass_kgha_fish_family_avg',
        ),
        migrations.RenameField(
            model_name='beltfishsemodel',
            old_name='biomass_kgha_by_fish_family_sd',
            new_name='biomass_kgha_fish_family_sd',
        ),
        migrations.RenameField(
            model_name='beltfishsemodel',
            old_name='biomass_kgha_by_trophic_group_avg',
            new_name='biomass_kgha_trophic_group_avg',
        ),
        migrations.RenameField(
            model_name='beltfishsemodel',
            old_name='biomass_kgha_by_trophic_group_sd',
            new_name='biomass_kgha_trophic_group_sd',
        ),
        migrations.RenameField(
            model_name='beltfishsumodel',
            old_name='biomass_kgha_by_fish_family',
            new_name='biomass_kgha_fish_family',
        ),
        migrations.RenameField(
            model_name='beltfishsumodel',
            old_name='biomass_kgha_by_fish_family_zeroes',
            new_name='biomass_kgha_fish_family_zeroes',
        ),
        migrations.RenameField(
            model_name='beltfishsumodel',
            old_name='biomass_kgha_by_trophic_group',
            new_name='biomass_kgha_trophic_group',
        ),
        migrations.RenameField(
            model_name='beltfishsumodel',
            old_name='biomass_kgha_by_trophic_group_zeroes',
            new_name='biomass_kgha_trophic_group_zeroes',
        ),
        migrations.RenameField(
            model_name='benthiclitsemodel',
            old_name='percent_cover_by_benthic_category_avg',
            new_name='percent_cover_benthic_category_avg',
        ),
        migrations.RenameField(
            model_name='benthiclitsemodel',
            old_name='percent_cover_by_benthic_category_sd',
            new_name='percent_cover_benthic_category_sd',
        ),
        migrations.RenameField(
            model_name='benthiclitsumodel',
            old_name='percent_cover_by_benthic_category',
            new_name='percent_cover_benthic_category',
        ),
        migrations.RenameField(
            model_name='benthicphotoquadrattransectsemodel',
            old_name='percent_cover_by_benthic_category_avg',
            new_name='percent_cover_benthic_category_avg',
        ),
        migrations.RenameField(
            model_name='benthicphotoquadrattransectsemodel',
            old_name='percent_cover_by_benthic_category_sd',
            new_name='percent_cover_benthic_category_sd',
        ),
        migrations.RenameField(
            model_name='benthicphotoquadrattransectsumodel',
            old_name='percent_cover_by_benthic_category',
            new_name='percent_cover_benthic_category',
        ),
        migrations.RenameField(
            model_name='benthicpitsemodel',
            old_name='percent_cover_by_benthic_category_avg',
            new_name='percent_cover_benthic_category_avg',
        ),
        migrations.RenameField(
            model_name='benthicpitsemodel',
            old_name='percent_cover_by_benthic_category_sd',
            new_name='percent_cover_benthic_category_sd',
        ),
        migrations.RenameField(
            model_name='benthicpitsumodel',
            old_name='percent_cover_by_benthic_category',
            new_name='percent_cover_benthic_category',
        ),
    ]
