# Generated by Django 2.2.12 on 2020-06-01 19:24

from django.db import migrations
from ..models.view_models import (
    BenthicLITObsView,
    BenthicLITSUView,
    BenthicLITSEView,
    BleachingQCColoniesBleachedObsView,
    BleachingQCQuadratBenthicPercentObsView,
    BleachingQCSUView,
    BleachingQCSEView,
    HabitatComplexityObsView,
    HabitatComplexitySUView,
    HabitatComplexitySEView,
)

drop_obs_lit = "DROP VIEW IF EXISTS vw_benthiclit_obs;"
drop_su_lit = "DROP VIEW IF EXISTS vw_benthiclit_su;"
drop_se_lit = "DROP VIEW IF EXISTS vw_benthiclit_se;"
drop_obs_qc1 = "DROP VIEW IF EXISTS vw_bleachingqc_colonies_bleached_obs;"
drop_obs_qc2 = "DROP VIEW IF EXISTS vw_bleachingqc_quadrat_benthic_percent_obs;"
drop_su_qc = "DROP VIEW IF EXISTS vw_bleachingqc_su;"
drop_se_qc = "DROP VIEW IF EXISTS vw_bleachingqc_se;"
drop_obs_hab = "DROP VIEW IF EXISTS vw_habitatcomplexity_obs;"
drop_su_hab = "DROP VIEW IF EXISTS vw_habitatcomplexity_su;"
drop_se_hab = "DROP VIEW IF EXISTS vw_habitatcomplexity_se;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200526_1409'),
    ]

    operations = [
        migrations.RunSQL(BenthicLITObsView.sql, drop_obs_lit),
        migrations.RunSQL(BenthicLITSUView.sql, drop_su_lit),
        migrations.RunSQL(BenthicLITSEView.sql, drop_se_lit),
        migrations.RunSQL(BleachingQCColoniesBleachedObsView.sql, drop_obs_qc1),
        migrations.RunSQL(BleachingQCQuadratBenthicPercentObsView.sql, drop_obs_qc2),
        migrations.RunSQL(BleachingQCSUView.sql, drop_su_qc),
        migrations.RunSQL(BleachingQCSEView.sql, drop_se_qc),
        migrations.RunSQL(HabitatComplexityObsView.sql, drop_obs_hab),
        migrations.RunSQL(HabitatComplexitySUView.sql, drop_su_hab),
        migrations.RunSQL(HabitatComplexitySEView.sql, drop_se_hab),
    ]
