# Generated by Django 2.2.12 on 2020-06-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200528_1408'),
        ('api', '0027_auto_20200526_1409'),
    ]

    operations = [
    ]
