# Generated by Django 3.2.20 on 2023-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_auto_20231020_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitatcomplexitysumodel",
            name="score_sd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_algae_sd",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_hard_sd",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_soft_sd",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0, max_digits=4, null=True
            ),
        ),
    ]
