# Generated by Django 3.2.20 on 2023-11-09 22:35

from django.db import migrations
from api.models.revisions import forward_sql


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20231024_1538'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, ""),
    ]
