# Generated by Django 2.2.12 on 2020-06-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_benthiclitobsview_benthiclitseview_benthiclitsuview_bleachingqccoloniesbleachedobsview_bleachingqcqu'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishsize',
            name='max_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishsize',
            name='min_val',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
