# Generated by Django 2.2.12 on 2020-06-08 14:27

from django.db import migrations


min_max_vals = {
    "00c0bb86-00d5-4f65-b152-51c47d44d413": ["0 ", "5"],
    "0b251484-6c44-4942-8fb0-d43ee2a8271d": ["5 ", "10"],
    "6b7c3649-c3b8-4c19-90b0-be21d1f119a9": ["10 ", "15"],
    "70f7cf9f-ad64-4d60-aef5-b6f33a0a1e38": ["15 ", "20"],
    "7336a45b-ce00-4d61-b00c-26303f4ea6b0": ["20 ", "25"],
    "ed8d763c-6d7a-4553-ad80-1b10db421576": ["25 ", "30"],
    "e4160948-7e3b-466b-bc83-c75ff2756f3e": ["30 ", "35"],
    "ef217fc6-2553-4749-80d9-a54bcdce96c0": ["35 ", "40"],
    "e0167892-cfad-4ba5-a529-c06a041eaa8b": ["40 ", "45"],
    "232b4dc0-320d-4793-a67d-fa3fca94cebf": ["45 ", "50"],
    "7953208c-4856-4863-b011-dd692b3bf7a6": ["0 ", "10"],
    "4f131505-9d35-41f7-a70d-3fff0e7de1cd": ["10 ", "20"],
    "b157bdc8-92bf-4922-9612-fea464f2fcc0": ["20 ", "30"],
    "0623d433-2c3b-4d33-8a88-e081795350a0": ["30 ", "40"],
    "6ff87e94-152d-485c-881b-df40a60db7df": ["40 ", "50"],
    "631670a2-9950-446a-ad6a-6284ae471a10": ["50"],
    "3cf72cca-cd31-406f-a78d-b05586ec8621": ["50"],
    "2035e4e0-f4bf-45fb-bf3f-17e0e0626802": ["0 ", "5"],
    "7084099e-1db3-462b-b685-0267ae04c66c": ["6 ", "10"],
    "1002c522-3796-4b22-a3f3-9d91a1bd9acf": ["11 ", "20"],
    "a039ee83-783e-4db9-afe3-e12d694a0286": ["21 ", "30"],
    "130486ae-59b0-4fe0-8cba-c3a2fbcf432e": ["31 ", "40"],
    "0a8b9d6c-a2e5-4dad-834e-6767e7569720": ["41 ", "50"],
    "684870b5-92c2-4d20-b312-39d9681bee79": ["50"],
}


def set_fishsize_min_max(apps, schemaeditor):
    FishSize = apps.get_model('api', 'FishSize')
    for pk, vals in min_max_vals.items():
        try:
            fs = FishSize.objects.get(id=pk)
        except FishSize.DoesNotExist:
            pass
        if fs is None:
            continue
        fs.min_val = vals[0]
        if len(vals) == 2:
            fs.max_val = vals[1]
        fs.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0030_auto_20200605_2044")]

    operations = [migrations.RunPython(set_fishsize_min_max, migrations.RunPython.noop)]
