# Generated by Django 3.2.20 on 2023-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_auto_20231110_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_100_avg",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_100_sd",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_20_avg",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_20_sd",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_50_avg",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_50_sd",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_80_avg",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_80_sd",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_dead_avg",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="percent_dead_sd",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_100",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_20",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_50",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_80",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="bleachingqcsumodel",
            name="percent_dead",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
