# Generated by Django 3.2.20 on 2023-11-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20231108_1528'),
        ('api', '0031_auto_20231112_1910'),
    ]

    operations = [
    ]
