# Generated by Django 2.2.12 on 2020-07-17 19:19

import api.models.mermaid
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200608_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='benthictransect',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Current'),
        ),
        migrations.AddField(
            model_name='benthictransect',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
        ),
        migrations.AddField(
            model_name='benthictransect',
            name='relative_depth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.RelativeDepth'),
        ),
        migrations.AddField(
            model_name='benthictransect',
            name='sample_time',
            field=models.TimeField(blank=True, default=api.models.mermaid.default_time, null=True),
        ),
        migrations.AddField(
            model_name='benthictransect',
            name='tide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tide'),
        ),
        migrations.AddField(
            model_name='benthictransect',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Visibility'),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Current'),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='relative_depth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.RelativeDepth'),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='sample_time',
            field=models.TimeField(blank=True, default=api.models.mermaid.default_time, null=True),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='tide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tide'),
        ),
        migrations.AddField(
            model_name='fishbelttransect',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Visibility'),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Current'),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='relative_depth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.RelativeDepth'),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='sample_time',
            field=models.TimeField(blank=True, default=api.models.mermaid.default_time, null=True),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='tide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tide'),
        ),
        migrations.AddField(
            model_name='quadratcollection',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Visibility'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='validations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sampleevent',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='depth (m)'),
        ),
        migrations.AlterField(
            model_name='sampleevent',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Management'),
        ),
        migrations.AlterField(
            model_name='sampleevent',
            name='sample_date',
            field=models.DateField(blank=True, default=api.models.mermaid.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='sampleevent',
            name='sample_time',
            field=models.TimeField(blank=True, default=api.models.mermaid.default_time, null=True),
        ),
        migrations.AlterField(
            model_name='sampleevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_events', to='api.Site'),
        ),
    ]
