# Generated by Django 2.2.12 on 2020-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200623_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belttransectwidth',
            name='val',
        ),
        migrations.AlterField(
            model_name='belttransectwidth',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
