# Generated by Django 2.2.12 on 2020-06-10 21:04

from django.db import migrations


def update_record(sample_event, sample_unit):
    sample_unit.sample_time = sample_event.sample_time
    sample_unit.depth = sample_event.depth
    sample_unit.visibility = sample_event.visibility
    sample_unit.current = sample_event.current
    sample_unit.relative_depth = sample_event.relative_depth
    sample_unit.tide = sample_event.tide
    sample_unit.save()


def migrate_sample_event_to_sample_unit(apps, schema_editor):
    SampleEvent = apps.get_model("api", "SampleEvent")
    for se in SampleEvent.objects.all():
        for bt in se.benthictransect_set.all():
            update_record(se, bt)

        for ft in se.fishbelttransect_set.all():
            update_record(se, ft)

        for qc in se.quadratcollection_set.all():
            update_record(se, qc)


class Migration(migrations.Migration):

    dependencies = [("api", "0032_auto_20200610_2203")]

    operations = [
        migrations.RunPython(
            migrate_sample_event_to_sample_unit, migrations.RunPython.noop
        )
    ]
