# Generated by Django 3.2.20 on 2024-03-26 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_fishattributeview_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarysampleeventmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
