# Generated by Django 2.2.12 on 2020-06-10 21:04

from django.db import migrations

from api.utils.sample_units import migrate_collect_record_sample_event


def update_record(sample_event, sample_unit):
    sample_unit.sample_time = sample_event.sample_time
    sample_unit.depth = sample_event.depth
    sample_unit.visibility = sample_event.visibility
    sample_unit.current = sample_event.current
    sample_unit.relative_depth = sample_event.relative_depth
    sample_unit.tide = sample_event.tide
    sample_unit.save()


def migrate_sample_event_to_sample_unit(apps, schema_editor):
    SampleEvent = apps.get_model("api", "SampleEvent")
    for se in SampleEvent.objects.all():
        for bt in se.benthictransect_set.all():
            update_record(se, bt)

        for ft in se.fishbelttransect_set.all():
            update_record(se, ft)

        for qc in se.quadratcollection_set.all():
            update_record(se, qc)


def migrate_collect_record(apps, schema_editor):
    CollectRecord = apps.get_model("api", "CollectRecord")
    for cr in CollectRecord.objects.all():
        if isinstance(cr.data.get("sample_event"), str):
            continue
        migrate_collect_record_sample_event(cr)
        cr.save()



class Migration(migrations.Migration):

    dependencies = [("api", "0033_sampleevent_validations")]

    operations = [
        migrations.RunPython(
            migrate_sample_event_to_sample_unit, migrations.RunPython.noop
        ),
        migrations.RunPython(

            migrate_collect_record, migrations.RunPython.noop
        )
    ]
