# Generated by Django 3.2.20 on 2024-04-17 17:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import api.models.gfcr


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_auto_20240415_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="indicator_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_solutions",
                to="api.gfcrindicatorset",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="sustainable_finance_mechanisms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("biodiversity_offsets", "Biodiversity offsets"),
                        ("blue_bonds", "Blue bonds"),
                        ("blue_carbon", "Blue carbon"),
                        ("conservation_trust_funds", "Conservation trust funds"),
                        ("debt_conversion", "Debt conversion"),
                        ("incubator_tecnical_assistance", "Incubator / Technical assistance"),
                        ("insurance_products", "Insurance products"),
                        ("mpa_entry_fees", "MPA entry fees"),
                        ("pay_for_success", "Pay for success"),
                        ("sustainable_livelihood_mech", "Sustainable livelihood mechanisms"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                validators=[api.models.gfcr.validate_unique_elements],
            ),
        ),
        migrations.AlterField(
            model_name="gfcrinvestmentsource",
            name="finance_solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investment_sources",
                to="api.gfcrfinancesolution",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrinvestmentsource",
            name="investment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Investment amount in USD"
            ),
        ),
        migrations.AlterField(
            model_name="gfcrrevenue",
            name="annual_revenue",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=11, verbose_name="Annual revenue in USD"
            ),
        ),
        migrations.AlterField(
            model_name="gfcrrevenue",
            name="finance_solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenues",
                to="api.gfcrfinancesolution",
            ),
        ),
    ]
