# Generated by Django 3.2.20 on 2024-04-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_auto_20240415_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="indicator_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_solutions",
                to="api.gfcrindicatorset",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrinvestmentsource",
            name="finance_solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investment_sources",
                to="api.gfcrfinancesolution",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrinvestmentsource",
            name="investment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Investment amount in USD"
            ),
        ),
        migrations.AlterField(
            model_name="gfcrrevenue",
            name="annual_revenue",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=11, verbose_name="Annual revenue in USD"
            ),
        ),
        migrations.AlterField(
            model_name="gfcrrevenue",
            name="finance_solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenues",
                to="api.gfcrfinancesolution",
            ),
        ),
    ]
