# Generated by Django 2.2.12 on 2020-07-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200618_1448'),
        ('api', '0032_auto_20200623_1311'),
    ]

    operations = [
    ]
