# Generated by Django 3.2.20 on 2024-04-17 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_restrictedprojectsummarysampleevent_unrestrictedprojectsummarysampleevent"),
        ("api", "0035_auto_20240417_1713"),
        ("api", "0036_auto_20240417_1713"),
    ]

    operations = []
