# Generated by Django 2.2.12 on 2020-07-15 17:14

from django.db import migrations
from ..models.view_models import SampleEventViewModel


drop_se_view = "DROP VIEW IF EXISTS public.vw_sample_events CASCADE;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_management_access_restriction'),
    ]

    operations = [
        migrations.RunSQL(SampleEventViewModel.sql, drop_se_view),
    ]
