# Generated by Django 3.2.20 on 2024-04-19 18:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_merge_20240417_1959"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="includes_gfcr",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f4_end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f4_start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
