# Generated by Django 3.2.20 on 2024-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_auto_20240419_1818"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gfcrinvestmentsource",
            name="gender_smart",
        ),
        migrations.AddField(
            model_name="gfcrfinancesolution",
            name="gender_smart",
            field=models.BooleanField(default=False),
        ),
    ]
