# Generated by Django 3.2.20 on 2024-05-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_auto_20240430_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gfcrindicatorset",
            name="report_year",
        ),
        migrations.RemoveField(
            model_name="gfcrinvestmentsource",
            name="used_gfcr_funded_incubator",
        ),
        migrations.AddField(
            model_name="gfcrfinancesolution",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f1_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f2_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f3_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f4_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f5_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f6_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrindicatorset",
            name="f7_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrinvestmentsource",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gfcrrevenue",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="used_an_incubator",
            field=models.CharField(
                blank=True,
                choices=[("gfcr_funded", "GFCR-funded"), ("non_gfcr_funded", "Non-GFCR-funded")],
                max_length=50,
                null=True,
            ),
        ),
    ]
