# Generated by Django 3.2.20 on 2024-06-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_auto_20240523_2232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benthicattribute",
            name="life_history",
        ),
        migrations.AddField(
            model_name="benthicattribute",
            name="life_histories",
            field=models.ManyToManyField(blank=True, to="api.BenthicLifeHistory"),
        ),
    ]
