# Generated by Django 3.2.20 on 2024-06-18 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_auto_20240612_2051"),
        ("api", "0041_auto_20240613_1200"),
    ]

    operations = []
