# Generated by Django 3.2.20 on 2024-06-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_merge_0041_auto_20240612_2051_0041_auto_20240613_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="benthicpitobsmodel",
            name="life_histories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthicpitsemodel",
            name="percent_cover_life_histories_avg",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthicpitsemodel",
            name="percent_cover_life_histories_sd",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthicpitsumodel",
            name="percent_cover_life_histories",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
