# Generated by Django 3.2.20 on 2024-07-12 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_alter_gfcrindicatorset_indicator_set_type"),
        ("api", "0043_auto_20240621_2045"),
    ]

    operations = []
