# Generated by Django 3.2.20 on 2024-07-17 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_merge_20240712_1819"),
        ("api", "0044_merge_20240716_1841"),
    ]

    operations = []
