# Generated by Django 3.2.20 on 2024-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_merge_20240712_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="project_name",
            field=models.CharField(default="awaiting refresh", max_length=255),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="project_name",
            field=models.CharField(default="awaiting refresh", max_length=255),
        ),
    ]
