# Generated by Django 3.2.20 on 2024-07-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20240717_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='growth_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.growthform'),
        ),
    ]
