# Generated by Django 3.2.20 on 2024-07-23 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_auto_20240717_2130"),
        ("api", "0047_auto_20240717_2031"),
    ]

    operations = []
