# Generated by Django 3.2.20 on 2024-07-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_merge_0045_auto_20240717_2130_0047_auto_20240717_2031"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="observation",
        ),
        migrations.AddField(
            model_name="image",
            name="original_image_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="obsbenthicphotoquadrat",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obs_benthic_photo_quadrats",
                to="api.image",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
