# Generated by Django 3.2.20 on 2024-07-25 20:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_auto_20240723_2136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("benthic_attribute", "growth_form")},
        ),
        migrations.CreateModel(
            name="LabelMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("CoralNet", "CoralNet"), ("ReefCloud", "ReefCloud")],
                        max_length=50,
                    ),
                ),
                ("provider_id", models.CharField(max_length=255)),
                ("provider_label", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labelmapping_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="api.label",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labelmapping_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "class_label_mapping",
                "unique_together": {("label", "provider_id")},
            },
        ),
    ]
