# Generated by Django 3.2.20 on 2024-07-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20240723_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
