# Generated by Django 3.2.20 on 2024-07-25 21:08

from django.db import migrations


def create_initial_classifier(apps, schema_editor):
    Classifier = apps.get_model("api", "Classifier")
    Classifier.objects.create(
        name="initial pyspacer classifier",
        version="0.1",
        patch_size=224,
        num_points=25,
        description="Initial pyspacer classifier, trained using only public CoralNet public source data.",
    )


def remove_initial_classifier(apps, schema_editor):
    Classifier = apps.get_model("api", "Classifier")
    initial_classifier = Classifier.objects.get(name="initial pyspacer classifier")
    initial_classifier.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_labelmapping"),
    ]

    operations = [
        migrations.RunPython(create_initial_classifier, remove_initial_classifier),
    ]
