# Generated by Django 3.2.20 on 2024-07-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20240724_2150'),
        ('api', '0051_auto_20240725_2108'),
    ]

    operations = [
    ]
