# Generated by Django 3.2.20 on 2024-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20240808_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_machine_created',
            field=models.BooleanField(default=False),
        ),
    ]
