# Generated by Django 3.2.20 on 2024-08-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_auto_20240808_2117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltfishobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="beltfishsemodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthiclitobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsemodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthiclitsumodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsemodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthicphotoquadrattransectsumodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthicpitobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsemodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="benthicpitsumodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bleachingqccoloniesbleachedobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcquadratbenthicpercentobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsemodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bleachingqcsumodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexityobsmodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysemodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="habitatcomplexitysumodel",
            name="project_id",
            field=models.UUIDField(db_index=True),
        ),
    ]
