# Generated by Django 3.2.20 on 2024-08-16 18:54

from django.db import migrations, models

import api.models.classification


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_annotation_is_machine_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                max_length=255, storage=api.models.classification.select_image_storage, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                storage=api.models.classification.select_image_storage,
                upload_to="",
            ),
        ),
    ]
