# Generated by Django 3.2.20 on 2024-08-30 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_auto_20240823_2158"),
        ("api", "0056_auto_20240816_1854"),
    ]

    operations = []
