# Generated by Django 3.2.20 on 2024-08-25 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_merge_0055_auto_20240823_2158_0056_auto_20240816_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelmapping",
            name="benthic_attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labelmappings",
                to="api.benthicattribute",
            ),
        ),
        migrations.AddField(
            model_name="labelmapping",
            name="growth_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labelmappings",
                to="api.growthform",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labelmapping",
            unique_together={("benthic_attribute", "growth_form", "provider", "provider_id")},
        ),
        migrations.AlterField(
            model_name="labelmapping",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="api.label",
            ),
        ),
        migrations.CreateModel(
            name="BenthicAttributeGrowthForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "benthic_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benthic_attribute_growth_forms",
                        to="api.benthicattribute",
                    ),
                ),
                (
                    "growth_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benthic_attribute_growth_forms",
                        to="api.growthform",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "unique BA/GF combinations",
                "db_table": "benthic_attribute_growth_form",
                "ordering": ["benthic_attribute__name", "growth_form__name"],
                "unique_together": {("benthic_attribute", "growth_form")},
            },
        ),
        migrations.AddField(
            model_name="classifier",
            name="benthic_attribute_growth_forms",
            field=models.ManyToManyField(
                related_name="classifiers", to="api.BenthicAttributeGrowthForm"
            ),
        ),
    ]
