# Generated by Django 3.2.20 on 2024-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_merge_0055_auto_20240823_2158_0056_auto_20240816_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
