# Generated by Django 3.2.20 on 2024-08-25 20:36

from django.db import migrations


def dis_labels(apps, schema_editor):
    BenthicAttributeGrowthForm = apps.get_model("api", "BenthicAttributeGrowthForm")
    Classifier = apps.get_model("api", "Classifier")
    Label = apps.get_model("api", "Label")
    LabelMapping = apps.get_model("api", "LabelMapping")

    for lm in LabelMapping.objects.all():
        lm.benthic_attribute = lm.label.benthic_attribute
        lm.growth_form = lm.label.growth_form
        lm.save()

    for classifier in Classifier.objects.all():
        for label in classifier.labels.all():
            bagf, created = BenthicAttributeGrowthForm.objects.get_or_create(
                benthic_attribute=label.benthic_attribute, growth_form=label.growth_form
            )
            classifier.benthic_attribute_growth_forms.add(bagf)

    Label.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_auto_20240825_2036"),
    ]

    operations = [
        migrations.RunPython(dis_labels, migrations.RunPython.noop),
    ]
