# Generated by Django 3.2.20 on 2024-09-05 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_auto_20240825_2036"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benthicattributegrowthform",
            options={
                "ordering": ["benthic_attribute__name", "growth_form__name"],
                "verbose_name_plural": "BA/GF unique combinations",
            },
        ),
        migrations.RemoveField(
            model_name="classifier",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="labelmapping",
            name="label",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
    ]
