# Generated by Django 3.2.20 on 2024-09-09 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_auto_20240905_2123"),
        ("api", "0059_auto_20240825_2036"),
    ]

    operations = []
