# Generated by Django 3.2.20 on 2024-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0062_auto_20240917_1950"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitatcomplexitysemodel",
            name="observation_count_avg",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habitatcomplexitysemodel",
            name="observation_count_sd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="habitatcomplexitysumodel",
            name="observation_count",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
