# Generated by Django 3.2.20 on 2024-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0064_benthicphotoquadrattransect_image_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="benthiclitobsmodel",
            name="life_histories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthiclitsumodel",
            name="percent_cover_life_histories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthiclitsemodel",
            name="percent_cover_life_histories_avg",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthiclitsemodel",
            name="percent_cover_life_histories_sd",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
