# Generated by Django 3.2.20 on 2024-10-16 20:21

from django.db import migrations, models

import api.models.classification


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0065_image_annotations_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="feature_vector_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=api.models.classification.select_image_storage,
                upload_to="",
            ),
        ),
    ]
