# Generated by Django 3.2.20 on 2024-10-17 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0066_benthiclitobsmodel_life_histories"),
        ("api", "0066_image_feature_vector_file"),
    ]

    operations = []
