# Generated by Django 3.2.20 on 2024-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0067_merge_20241017_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="beltfishsemodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthiclitsemodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthicphotoquadrattransectsemodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benthicpitsemodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bleachingqcsemodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitatcomplexitysemodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="summarysampleeventmodel",
            name="observers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
