# Generated by Django 3.2.20 on 2024-11-11 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0068_auto_20241028_2238"),
        ("api", "0068_auto_20241031_2238"),
    ]

    operations = []
