# Generated by Django 3.2.20 on 2024-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0070_auto_20241111_1953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f4_3",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=5,
                verbose_name="Average reef fish biomass (kg/ha)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f5_3",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of local scientific/research partners involved in strengthening capacity for participation and co-development",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f5_5",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of agreements with local authorities or fishing cooperatives to manage marine resources",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f5_6",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of national policies linked to GFCR engagement"
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, age, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, age, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of direct jobs created (disaggregated by gender, age, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of direct jobs created (disaggregated by gender, age, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, age, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, age, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, age, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, age, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total direct beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total direct beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, age, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_3",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of financial mechanisms/reforms to help coastal communities respond and recover from external shocks",
            ),
        ),
    ]
