# Generated by Django 3.2.20 on 2024-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0071_auto_20241112_2144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2a",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2b",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2c",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2d",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
    ]
