# Generated by Django 3.2.20 on 2024-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0072_auto_20241113_1325"),
    ]

    operations = [
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="project_admins",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="project_admins",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="data_policy_beltfish",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="data_policy_benthiclit",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="data_policy_benthicpit",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="data_policy_benthicpqt",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="data_policy_bleachingqc",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="data_policy_habitatcomplexity",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="project_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="data_policy_beltfish",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="data_policy_benthiclit",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="data_policy_benthicpit",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="data_policy_benthicpqt",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="data_policy_bleachingqc",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="data_policy_habitatcomplexity",
            field=models.CharField(default="awaiting refresh", max_length=50),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="project_notes",
            field=models.TextField(blank=True),
        ),
    ]
