# Generated by Django 3.2.20 on 2024-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0073_auto_20241114_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltfishobsmodel",
            name="biomass_kgha",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="biomass (kg/ha)",
            ),
        ),
        migrations.AlterField(
            model_name="beltfishsumodel",
            name="biomass_kgha",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name="biomass (kg/ha)",
            ),
        ),
        migrations.AlterField(
            model_name="beltfishsemodel",
            name="biomass_kgha_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name="biomass mean (kg/ha)",
            ),
        ),
        migrations.AlterField(
            model_name="beltfishsemodel",
            name="biomass_kgha_sd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name="biomass standard deviation (kg/ha)",
            ),
        ),
    ]
