# Generated by Django 3.2.20 on 2024-12-03 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0073_auto_20241126_1547"),
        ("api", "0074_auto_20241129_1516"),
    ]

    operations = []
