# Generated by Django 3.2.20 on 2024-12-05 22:42

from django.db import migrations


def migrate_gfcr_nulls(apps, schema_editor):
    GFCRIndicatorSet = apps.get_model("api", "GFCRIndicatorSet")
    for g in GFCRIndicatorSet.objects.all():
        if g.f3_5c is None:
            g.f3_5c = 0
        if g.f3_5d is None:
            g.f3_5d = 0
        if g.f5_4c is None:
            g.f5_4c = 0
        if g.f5_4d is None:
            g.f5_4d = 0
        if g.f6_1c is None:
            g.f6_1c = 0
        if g.f6_1d is None:
            g.f6_1d = 0
        if g.f6_2c is None:
            g.f6_2c = 0
        if g.f6_2d is None:
            g.f6_2d = 0
        if g.f7_1c is None:
            g.f7_1c = 0
        if g.f7_1d is None:
            g.f7_1d = 0
        if g.f7_2c is None:
            g.f7_2c = 0
        if g.f7_2d is None:
            g.f7_2d = 0
        g.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0075_merge_0073_auto_20241126_1547_0074_auto_20241129_1516"),
    ]

    operations = [
        migrations.RunPython(migrate_gfcr_nulls, migrations.RunPython.noop),
    ]
