# Generated by Django 3.2.20 on 2024-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0076_auto_20241205_2242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benthicpit",
            name="interval_size",
            field=models.DecimalField(
                decimal_places=2, default=0.5, max_digits=4, verbose_name="interval size (m)"
            ),
        ),
        migrations.AlterField(
            model_name="benthictransect",
            name="depth",
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name="depth (m)"),
        ),
        migrations.AlterField(
            model_name="fishbelttransect",
            name="depth",
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name="depth (m)"),
        ),
        migrations.AlterField(
            model_name="fishspecies",
            name="climate_score",
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="fishspecies",
            name="max_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="maximum length (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="fishspecies",
            name="trophic_level",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="fishspecies",
            name="vulnerability",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f3_5c",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of people engaged in coral reef restoration [youth]"
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f3_5d",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of people engaged in coral reef restoration [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f5_4c",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of local practitioners trained / supported in coral reef conservation and management [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f5_4d",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="Number of local practitioners trained / supported in coral reef conservation and management [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1a",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1b",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1c",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_1d",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of direct jobs created (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2a",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2b",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2c",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f6_2d",
            field=models.IntegerField(
                default=0,
                verbose_name="Number of people with increased income and/or nutrition from GFCR support (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1a",
            field=models.IntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1b",
            field=models.IntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1c",
            field=models.IntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_1d",
            field=models.IntegerField(
                default=0,
                verbose_name="Total direct beneficiaries (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2a",
            field=models.IntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [men]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2b",
            field=models.IntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [women]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2c",
            field=models.IntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [youth]",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f7_2d",
            field=models.IntegerField(
                default=0,
                verbose_name="Total indirect beneficiaries (disaggregated by gender, youth, Indigenous peoples) [indigenous]",
            ),
        ),
        migrations.AlterField(
            model_name="habitatcomplexity",
            name="interval_size",
            field=models.DecimalField(
                decimal_places=2, default=0.5, max_digits=4, verbose_name="interval size (m)"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="est_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="year established"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="size",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True, verbose_name="Size (ha)"
            ),
        ),
        migrations.AlterField(
            model_name="obsbeltfish",
            name="size",
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name="size (cm)"),
        ),
        migrations.AlterField(
            model_name="quadratcollection",
            name="depth",
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name="depth (m)"),
        ),
        migrations.AlterField(
            model_name="quadratcollection",
            name="quadrat_size",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=6, verbose_name="single quadrat area (m2)"
            ),
        ),
        migrations.AlterField(
            model_name="quadrattransect",
            name="depth",
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name="depth (m)"),
        ),
        migrations.AlterField(
            model_name="quadrattransect",
            name="quadrat_size",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=6, verbose_name="single quadrat area (m2)"
            ),
        ),
    ]
