# Generated by Django 3.2.20 on 2025-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0078_project_user_citation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="sector",
            field=models.CharField(
                choices=[
                    ("banking_and_finance", "Banking and finance"),
                    ("clean_energy", "Clean energy"),
                    ("coastal_agriculture", "Coastal agriculture"),
                    ("coastal_forestry", "Coastal forestry"),
                    ("coastal_infrastructure", "Coastal infrastructure"),
                    ("coral_ecosystem_restoration", "Coral ecosystem restoration"),
                    ("ecotourism", "Ecotourism"),
                    ("green_shipping_and_cruise_ships", "Green shipping and cruise ships"),
                    ("invasive_species_management", "Invasive species management"),
                    (
                        "marine_protected_areas",
                        "Marine Protected Areas and other effectively managed marine areas",
                    ),
                    (
                        "other_land_based_pollutants_management",
                        "Other land-based pollutants management",
                    ),
                    ("plastic_waste_management", "Plastic waste management"),
                    ("sewage_and_waste_water_treatment", "Sewage and waste-water treatment"),
                    ("sustainable_fisheries", "Sustainable fisheries"),
                    ("sustainable_mariculture_aquaculture", "Sustainable mariculture/aquaculture"),
                    ("water_provision", "Water provision"),
                    (
                        "ce_pollution_mitigation",
                        "Circular Economy and Pollution Management - Pollution Mitigation",
                    ),
                    (
                        "ce_sustainable_infrastructure",
                        "Circular Economy and Pollution Management - Sustainable Infrastructure",
                    ),
                    (
                        "ce_waste_management",
                        "Circular Economy and Pollution Management - Waste Management",
                    ),
                    ("fm_biodiversity_credits", "Financial Mechanisms - Biodiversity Credits"),
                    ("fm_blue_carbon_credits", "Financial Mechanisms - Blue Carbon Credits"),
                    (
                        "fm_conservation_trust_fund",
                        "Financial Mechanisms - Conservation Trust Fund",
                    ),
                    ("fm_insurance_mechanisms", "Financial Mechanisms - Insurance Mechanisms"),
                    ("fm_mpa_user_fee", "Financial Mechanisms - MPA User Fee"),
                    ("fm_resilience_credits", "Financial Mechanisms - Resilience Credits"),
                    (
                        "sc_coastal_infrastructure",
                        "Sustainable Coastal Development - Coastal Infrastructure",
                    ),
                    (
                        "sc_coral_restoration_revenue_models",
                        "Sustainable Coastal Development - Coral Restoration Revenue Models",
                    ),
                    ("sc_ecotourism", "Sustainable Coastal Development - Ecotourism"),
                    ("so_aquaculture", "Sustainable Ocean Production - Aquaculture"),
                    ("so_fisheries", "Sustainable Ocean Production - Fisheries"),
                    (
                        "so_marine_biotechnology_products",
                        "Sustainable Ocean Production - Marine Biotechnology Products",
                    ),
                    ("so_other", "Sustainable Ocean Production - Other"),
                    (
                        "so_sustainable_small_scale_fisheries",
                        "Sustainable Ocean Production - Sustainable Small-Scale Fisheries",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
