# Generated by Django 3.2.20 on 2025-01-22 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0080_alter_gfcrfinancesolution_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gfcrindicatorset",
            name="f6_2a",
        ),
        migrations.RemoveField(
            model_name="gfcrindicatorset",
            name="f6_2b",
        ),
        migrations.RemoveField(
            model_name="gfcrindicatorset",
            name="f6_2c",
        ),
        migrations.RemoveField(
            model_name="gfcrindicatorset",
            name="f6_2d",
        ),
    ]
