# Generated by Django 3.2.20 on 2025-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0081_auto_20250122_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryCacheQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("project_id", models.UUIDField()),
                ("processing", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "summary_cache_queue",
                "unique_together": {("project_id", "processing")},
            },
        ),
    ]
