# Generated by Django 3.2.20 on 2025-01-31 16:38

from django.db import migrations


def migrate_old_sectors(apps, schema_editor):
    GFCRFinanceSolution = apps.get_model("api", "GFCRFinanceSolution")

    for name in ["asdf", "Alex solution"]:
        GFCRFinanceSolution.objects.filter(name=name).delete()

    sector_mapping = {
        "banking_and_finance": "fm_other",
        "coral_ecosystem_restoration": "sc_coral_restoration_revenue_models",
        "invasive_species_management": "so_other",
        "sewage_and_waste_water_treatment": "ce_waste_management",
        "water_provision": "sc_other",
    }

    for old_sector, new_sector in sector_mapping.items():
        GFCRFinanceSolution.objects.filter(sector=old_sector).update(sector=new_sector)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0082_summarycachequeue"),
    ]

    operations = [
        migrations.RunPython(migrate_old_sectors, migrations.RunPython.noop),
    ]
