# Generated by Django 3.2.20 on 2025-01-31 17:23

from django.db import migrations


def migrate_old_sectors(apps, schema_editor):
    GFCRFinanceSolution = apps.get_model("api", "GFCRFinanceSolution")

    for name in ["asdf", "Alex solution"]:
        GFCRFinanceSolution.objects.filter(name=name).delete()

    sector_mapping = {
        "coastal_infrastructure": "sc_coastal_infrastructure",
        "ecotourism": "sc_ecotourism",
        "marine_protected_areas": "so_other",
        "other_land_based_pollutants_management": "so_other",
        "plastic_waste_management": "ce_waste_management",
        "sustainable_fisheries": "so_fisheries",
        "sustainable_mariculture_aquaculture": "so_aquaculture",
    }

    for old_sector, new_sector in sector_mapping.items():
        GFCRFinanceSolution.objects.filter(sector=old_sector).update(sector=new_sector)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0083_auto_20250131_1638"),
    ]

    operations = [
        migrations.RunPython(migrate_old_sectors, migrations.RunPython.noop),
    ]
