# Generated by Django 3.2.20 on 2025-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0084_auto_20250131_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="sector",
            field=models.CharField(
                choices=[
                    (
                        "ce_pollution_mitigation",
                        "Circular Economy and Pollution Management - Pollution Mitigation",
                    ),
                    (
                        "ce_sustainable_infrastructure",
                        "Circular Economy and Pollution Management - Sustainable Infrastructure",
                    ),
                    (
                        "ce_waste_management",
                        "Circular Economy and Pollution Management - Waste Management",
                    ),
                    ("ce_other", "Circular Economy and Pollution Management - Other"),
                    ("fm_biodiversity_credits", "Financial Mechanisms - Biodiversity Credits"),
                    ("fm_blue_carbon_credits", "Financial Mechanisms - Blue Carbon Credits"),
                    (
                        "fm_conservation_trust_fund",
                        "Financial Mechanisms - Conservation Trust Fund",
                    ),
                    ("fm_insurance_mechanisms", "Financial Mechanisms - Insurance Mechanisms"),
                    ("fm_mpa_user_fee", "Financial Mechanisms - MPA User Fee"),
                    ("fm_resilience_credits", "Financial Mechanisms - Resilience Credits"),
                    ("fm_other", "Financial Mechanisms - Other"),
                    (
                        "sc_coastal_infrastructure",
                        "Sustainable Coastal Development - Coastal Infrastructure",
                    ),
                    (
                        "sc_coral_restoration_revenue_models",
                        "Sustainable Coastal Development - Coral Restoration Revenue Models",
                    ),
                    ("sc_ecotourism", "Sustainable Coastal Development - Ecotourism"),
                    ("sc_other", "Sustainable Coastal Development - Other"),
                    ("so_aquaculture", "Sustainable Ocean Production - Aquaculture"),
                    ("so_fisheries", "Sustainable Ocean Production - Fisheries"),
                    ("so_mariculture", "Sustainable Ocean Production - Mariculture"),
                    (
                        "so_marine_biotechnology_products",
                        "Sustainable Ocean Production - Marine Biotechnology Products",
                    ),
                    ("so_other", "Sustainable Ocean Production - Other"),
                    (
                        "so_sustainable_small_scale_fisheries",
                        "Sustainable Ocean Production - Sustainable Small-Scale Fisheries",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
