# Generated by Django 3.2.20 on 2025-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0086_auto_20250213_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="restrictedprojectsummarysampleevent",
            name="project_includes_gfcr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unrestrictedprojectsummarysampleevent",
            name="project_includes_gfcr",
            field=models.BooleanField(default=False),
        ),
    ]
