# Generated by Django 3.2.20 on 2025-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0087_auto_20250219_1838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f1_1",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Total area of coral reefs in GFCR Programme (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_1a",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of MPAs and OECMs (as aligned to GBF Target 3) [coralreef] (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_1b",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of MPAs and OECMs (as aligned to GBF Target 3) [total] (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_2a",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of locally managed areas / co-managed areas [coralreef] (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_2b",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of locally managed areas / co-managed areas [total] (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_3a",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of fisheries management [coralreef] (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_3b",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of fisheries management [total] (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_4",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area with pollution mitigation (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f2_5",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of non-coral reef ecosystems, e.g., mangroves, seagrass or other associated ecosystems (sq.km)",
            ),
        ),
        migrations.AlterField(
            model_name="gfcrindicatorset",
            name="f3_1",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=11,
                verbose_name="Area of effective coral reef restoration (sq.km)",
            ),
        ),
    ]
