# Generated by Django 3.2.20 on 2025-09-17 19:37

from django.db import migrations

forward_sql = """
CREATE VIEW vw_project_summary_sample_events AS
SELECT *, 'restricted'::text AS access
FROM restricted_project_summary_se
UNION ALL
SELECT *, 'unrestricted'::text AS access
FROM unrestricted_project_summary_se;
"""
reverse_sql = """
DROP VIEW IF EXISTS vw_project_summary_sample_events;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0089_auto_20250630_2055"),
    ]

    operations = [
        migrations.RunSQL(sql=forward_sql, reverse_sql=reverse_sql),
    ]
