# Generated by Django 3.2.20 on 2025-09-17 19:37

from django.db import migrations

try:
    from api.models.summary_sample_events import ProjectSummarySampleEventView

    forward_sql = ProjectSummarySampleEventView.forward_sql
    reverse_sql = ProjectSummarySampleEventView.reverse_sql
except ImportError:
    forward_sql = ""
    reverse_sql = ""


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0089_auto_20250630_2055"),
    ]

    operations = [
        migrations.RunSQL(sql=forward_sql, reverse_sql=reverse_sql),
    ]
