# Generated by Django 3.2.20 on 2025-09-18 19:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0090_auto_20250917_1937"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSummarySampleEventView",
            fields=[
                ("project_id", models.UUIDField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(default="awaiting refresh", max_length=255)),
                ("project_admins", models.JSONField(blank=True, null=True)),
                ("project_notes", models.TextField(blank=True)),
                ("project_includes_gfcr", models.BooleanField(default=False)),
                ("suggested_citation", models.TextField(blank=True)),
                (
                    "data_policy_beltfish",
                    models.CharField(default="awaiting refresh", max_length=50),
                ),
                (
                    "data_policy_benthiclit",
                    models.CharField(default="awaiting refresh", max_length=50),
                ),
                (
                    "data_policy_benthicpit",
                    models.CharField(default="awaiting refresh", max_length=50),
                ),
                (
                    "data_policy_habitatcomplexity",
                    models.CharField(default="awaiting refresh", max_length=50),
                ),
                (
                    "data_policy_bleachingqc",
                    models.CharField(default="awaiting refresh", max_length=50),
                ),
                (
                    "data_policy_benthicpqt",
                    models.CharField(default="awaiting refresh", max_length=50),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "records",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("access", models.CharField(default="restricted", max_length=15)),
            ],
            options={
                "db_table": "vw_project_summary_sample_events",
                "managed": False,
            },
        ),
    ]
