# Generated by Django 3.2.20 on 2025-09-19 21:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0091_projectsummarysampleeventview"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="restrictedprojectsummarysampleevent",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["records"], name="restricted__records_2385a0_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="unrestrictedprojectsummarysampleevent",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["records"], name="unrestricte_records_52623f_gin"
            ),
        ),
    ]
