# Generated by Django 3.2.20 on 2025-10-20 21:13

from django.db import migrations


def backfill_interval_start(apps, schema_editor):
    """
    Backfill interval_start to equal interval_size for all existing HabitatComplexity records.
    This matches the default behavior in the CSV ingest serializer.
    """
    HabitatComplexity = apps.get_model("api", "HabitatComplexity")
    for hc in HabitatComplexity.objects.all():
        if hc.interval_start is not None:
            continue
        hc.interval_start = hc.interval_size
        hc.save(update_fields=["interval_start"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20251020_2113'),
    ]

    operations = [
        migrations.RunPython(backfill_interval_start, migrations.RunPython.noop),
    ]
