# Generated by Django 3.2.20 on 2025-11-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0094_backfill_habitatcomplexity_interval_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
