# Generated by Django 3.2.20 on 2025-11-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0095_project_is_demo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_demo", True)),
                fields=("created_by",),
                name="unique_demo_project_per_user",
            ),
        ),
    ]
