# Generated by Django 3.2.20 on 2025-11-04 00:07

from django.conf import settings
from django.db import migrations


def set_demo(apps, schema_editor):
    project_cls = apps.get_model("api", "Project")
    try:
        prj = project_cls.objects.get(id=settings.DEMO_PROJECT_ID)
        prj.is_demo = True
        prj.save()
    except project_cls.DoesNotExist:
        return


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0096_project_unique_demo_project_per_user"),
    ]

    operations = [
        migrations.RunPython(set_demo, migrations.RunPython.noop),
    ]
