# Generated by Django 3.2.20 on 2025-11-13 00:00

from django.db import migrations

from api.models.revisions import forward_sql, reverse_sql


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0097_auto_20251104_0007"),
    ]

    operations = [
        migrations.RunSQL(forward_sql, reverse_sql),
    ]
