# Generated by Django 4.2.23 on 2025-11-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_belttransectwidthcondition_unique_together_and_more'),
        ('api', '0097_auto_20251104_0007'),
    ]

    operations = [
    ]
