# Generated by Django 4.2.26 on 2025-12-03 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0098_fix_revision_concurrency"),
        ("api", "0098_merge_20251111_2104"),
    ]

    operations = []
