# Generated by Django 4.2.26 on 2025-12-02 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0098_merge_20251111_2104"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP EXTENSION IF EXISTS pg_trgm;",
            reverse_sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
        ),
    ]
