# Generated by Django 4.2.26 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0099_merge_20251203_2123"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="collect_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="explore_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
