# Generated by Django 4.2.26 on 2026-01-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0099_merge_20251203_2123"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("demo_project_prompt_dismissed", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_settings",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profile_app_settings",
            },
        ),
    ]
