# Generated by Django 4.2.26 on 2026-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0102_backfill_image_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="collect_state",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="explore_state",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
