# Generated by Django 4.2.26 on 2026-04-17 18:04

import django.contrib.postgres.fields
from django.db import migrations, models

import api.models.gfcr


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0104_backfill_exif_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfcrfinancesolution",
            name="sustainable_finance_mechanisms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("biodiversity_offsets", "Biodiversity credits"),
                        ("blue_bonds", "Blue bonds"),
                        ("blue_carbon", "Blue carbon credits"),
                        ("conservation_trust_funds", "Conservation trust funds"),
                        ("debt_conversion", "Debt conversion"),
                        (
                            "economic_instruments",
                            "Economic instruments (fines, penalties, taxes, subsidies, etc.)",
                        ),
                        ("financial_guarantees", "Financial guarantees"),
                        (
                            "incubator_tecnical_assistance",
                            "Incubator / Technical assistance facility",
                        ),
                        ("insurance_products", "Insurance products"),
                        ("microfinance", "Microfinance / village savings and loans"),
                        ("mpa_entry_fees", "MPA entry fees"),
                        ("pay_for_success", "Pay for success"),
                        ("resilience_credits", "Resilience credits"),
                        ("revolving_finance_facility", "Revolving finance facility"),
                        ("sustainable_livelihood_mech", "Sustainable livelihood mechanisms"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                validators=[api.models.gfcr.validate_unique_elements],
            ),
        ),
        migrations.AlterField(
            model_name="gfcrinvestmentsource",
            name="investment_type",
            field=models.CharField(
                choices=[
                    ("bond", "Bond"),
                    ("commercial_loan", "Commercial loan"),
                    ("concessional_loan", "Concessional loan"),
                    ("equity", "Equity"),
                    ("financial_guarantee", "Financial guarantee"),
                    ("grant", "Grant"),
                    ("public_budget", "Public budget"),
                    ("technical_assistance", "Technical assistance / in-kind"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="gfcrrevenue",
            name="revenue_type",
            field=models.CharField(
                choices=[
                    ("biodiversity_offsets", "Biodiversity credits"),
                    ("blue_bonds", "Blue bonds"),
                    (
                        "carbon_credits_environmental_services",
                        "Blue carbon credits / environmental services",
                    ),
                    ("conservation_trust_funds", "Conservation trust funds"),
                    ("debt_conversion", "Debt conversion"),
                    ("ecotourism", "Ecotourism sales"),
                    ("fees_and_payments", "Fees, tariffs, penalties, and other payments"),
                    ("green_tax", "Green tax"),
                    ("insurance_products", "Insurance products"),
                    (
                        "interest_investment_returns",
                        "Interest / investment returns (e.g., public, private equity)",
                    ),
                    (
                        "marine_resources_sales",
                        "Natural resource sales (e.g., fisheries or aquaculture)",
                    ),
                    ("misc_revenue_streams", "Misc. revenue streams"),
                    (
                        "sustainable_livelihood_mechanisms",
                        "Other sustainable livelihood mechanisms",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
