# Generated by Django 4.2.26 on 2026-04-23 21:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0105_alter_gfcr_choices_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltInvert",
            fields=[
                (
                    "transectmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.transectmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate belt transect",
                "verbose_name_plural": "macroinvertebrate belt transect observations",
                "db_table": "transectmethod_transectbeltinvert",
            },
            bases=("api.transectmethod",),
        ),
        migrations.CreateModel(
            name="InvertAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(90, "superuser approved"), (10, "proposed")], default=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "invert_attribute",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="data_policy_macroinvertebrate",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "private"), (50, "public summary"), (100, "public")], default=50
            ),
        ),
        migrations.CreateModel(
            name="InvertClass",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "macroinvertebrate class",
                "verbose_name_plural": "macroinvertebrate classes",
                "db_table": "invert_class",
                "ordering": ("name",),
            },
            bases=("api.invertattribute",),
        ),
        migrations.CreateModel(
            name="InvertFamily",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "macroinvertebrate family",
                "verbose_name_plural": "macroinvertebrate families",
                "db_table": "invert_family",
                "ordering": ("name",),
            },
            bases=("api.invertattribute",),
        ),
        migrations.CreateModel(
            name="InvertGenus",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="genera",
                        to="api.invertfamily",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate genus",
                "verbose_name_plural": "macroinvertebrate genera",
                "db_table": "invert_genus",
                "ordering": ("name",),
            },
            bases=("api.invertattribute",),
        ),
        migrations.CreateModel(
            name="InvertPhylum",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "macroinvertebrate phylum",
                "verbose_name_plural": "macroinvertebrate phyla",
                "db_table": "invert_phylum",
                "ordering": ("name",),
            },
            bases=("api.invertattribute",),
        ),
        migrations.CreateModel(
            name="ObsBeltInvert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="size (cm)",
                    ),
                ),
                (
                    "include",
                    models.BooleanField(
                        default=True, verbose_name="include observation in aggregations/analyses?"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "beltinvert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beltinvert_observations",
                        to="api.beltinvert",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "invert_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.invertattribute"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate belt transect observation",
                "db_table": "obs_transectbeltinvert",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="InvertSizeBin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("val", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate size bin",
                "verbose_name_plural": "macroinvertebrate size bins",
                "db_table": "invert_size_bin",
            },
        ),
        migrations.CreateModel(
            name="InvertSize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("val", models.FloatField()),
                ("min_val", models.FloatField(blank=True, null=True)),
                ("max_val", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "invert_bin_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.invertsizebin"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate size",
                "verbose_name_plural": "macroinvertebrate sizes",
                "db_table": "invert_size",
            },
        ),
        migrations.CreateModel(
            name="InvertHarvestType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate harvest type",
                "verbose_name_plural": "macroinvertebrate harvest types",
                "db_table": "invert_harvest_type",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="InvertGroupOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate group of interest",
                "verbose_name_plural": "macroinvertebrate groups of interest",
                "db_table": "invert_group_of_interest",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="InvertBeltTransectWidth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("val", models.DecimalField(decimal_places=1, max_digits=4)),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate belt transect width",
                "verbose_name_plural": "macroinvertebrate belt transect widths",
                "db_table": "invert_belt_transect_width",
                "ordering": ("val",),
            },
        ),
        migrations.CreateModel(
            name="InvertBeltTransect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("collect_record_id", models.UUIDField(blank=True, null=True)),
                ("sample_time", models.TimeField(blank=True, null=True)),
                (
                    "depth",
                    models.DecimalField(decimal_places=1, max_digits=3, verbose_name="depth (m)"),
                ),
                (
                    "len_surveyed",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="transect length surveyed (m)"
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(default=1)),
                ("label", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="api.profile",
                    ),
                ),
                (
                    "current",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.current",
                    ),
                ),
                (
                    "reef_slope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.reefslope",
                    ),
                ),
                (
                    "relative_depth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.relativedepth",
                    ),
                ),
                (
                    "sample_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.sampleevent"
                    ),
                ),
                (
                    "size_bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invertsizebin",
                        verbose_name="size bin (cm)",
                    ),
                ),
                (
                    "tide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tide",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="api.profile",
                    ),
                ),
                (
                    "visibility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.visibility",
                    ),
                ),
                (
                    "width",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invertbelttransectwidth",
                        verbose_name="width (m)",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate belt transect",
                "verbose_name_plural": "macroinvertebrate belt transects",
                "db_table": "transect_belt_invert",
            },
        ),
        migrations.AddField(
            model_name="beltinvert",
            name="transect",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beltinvert_method",
                to="api.invertbelttransect",
                verbose_name="macroinvertebrate belt transect",
            ),
        ),
        migrations.CreateModel(
            name="InvertSpecies",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "max_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="maximum size (cm)",
                    ),
                ),
                (
                    "max_length_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("arm length", "arm length"),
                            ("body length", "body length"),
                            ("carapace length", "carapace length"),
                            ("carapace width", "carapace width"),
                            ("mantle length", "mantle length"),
                            ("pedal disc diameter", "pedal disc diameter"),
                            ("shell length/diameter", "shell length/diameter"),
                            ("test diameter", "test diameter"),
                        ],
                        max_length=50,
                        verbose_name="measurement type",
                    ),
                ),
                (
                    "max_length_source",
                    models.CharField(blank=True, max_length=200, verbose_name="size source"),
                ),
                ("max_length_url", models.URLField(blank=True, verbose_name="size source URL")),
                ("notes", models.TextField(blank=True)),
                (
                    "genus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="species",
                        to="api.invertgenus",
                    ),
                ),
                (
                    "group_of_interest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invertgroupofinterest",
                    ),
                ),
                (
                    "harvest_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invertharvesttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate species",
                "verbose_name_plural": "macroinvertebrate species",
                "db_table": "invert_species",
                "ordering": ("genus", "name"),
            },
            bases=("api.invertattribute",),
        ),
        migrations.CreateModel(
            name="InvertOrder",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "invert_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="api.invertclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "macroinvertebrate order",
                "verbose_name_plural": "macroinvertebrate orders",
                "db_table": "invert_order",
                "ordering": ("name",),
            },
            bases=("api.invertattribute",),
        ),
        migrations.AddField(
            model_name="invertfamily",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="families",
                to="api.invertorder",
            ),
        ),
        migrations.AddField(
            model_name="invertclass",
            name="phylum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="api.invertphylum",
            ),
        ),
        migrations.AddConstraint(
            model_name="invertclass",
            constraint=models.UniqueConstraint(
                fields=("name", "phylum"), name="unique_invertclass_name_phylum"
            ),
        ),
        migrations.AddConstraint(
            model_name="invertfamily",
            constraint=models.UniqueConstraint(
                fields=("name", "order"), name="unique_invertfamily_name_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="invertgenus",
            constraint=models.UniqueConstraint(
                fields=("name", "family"), name="unique_invertgenus_name_family"
            ),
        ),
        migrations.AddConstraint(
            model_name="invertorder",
            constraint=models.UniqueConstraint(
                fields=("name", "invert_class"), name="unique_invertorder_name_invert_class"
            ),
        ),
        migrations.AddConstraint(
            model_name="invertspecies",
            constraint=models.UniqueConstraint(
                fields=("name", "genus"), name="unique_invertspecies_name_genus"
            ),
        ),
    ]
