from django.db import migrations, models

INVERT_BELT_TRANSECT_WIDTHS = [
    {"val": 2, "name": "2m"},
    {"val": 4, "name": "4m"},
    {"val": 5, "name": "5m"},
]

# Mirroring FishSizeBin/FishSize choices for bins 5 and 10; bin 1 has no sizes.
INVERT_SIZE_BINS = [
    {
        "val": "1",
        "sizes": [],
    },
    {
        "val": "5",
        "sizes": [
            {"name": "0 - 5", "val": 2.5, "min_val": 0.0, "max_val": 5.0},
            {"name": "5 - 10", "val": 7.5, "min_val": 5.0, "max_val": 10.0},
            {"name": "10 - 15", "val": 12.5, "min_val": 10.0, "max_val": 15.0},
            {"name": "15 - 20", "val": 17.5, "min_val": 15.0, "max_val": 20.0},
            {"name": "20 - 25", "val": 22.5, "min_val": 20.0, "max_val": 25.0},
            {"name": "25 - 30", "val": 27.5, "min_val": 25.0, "max_val": 30.0},
            {"name": "30 - 35", "val": 32.5, "min_val": 30.0, "max_val": 35.0},
            {"name": "35 - 40", "val": 37.5, "min_val": 35.0, "max_val": 40.0},
            {"name": "40 - 45", "val": 42.5, "min_val": 40.0, "max_val": 45.0},
            {"name": "45 - 50", "val": 47.5, "min_val": 45.0, "max_val": 50.0},
            {"name": "50 +", "val": 50.0, "min_val": 50.0, "max_val": None},
        ],
    },
    {
        "val": "10",
        "sizes": [
            {"name": "0 - 10", "val": 5.0, "min_val": 0.0, "max_val": 10.0},
            {"name": "10 - 20", "val": 15.0, "min_val": 10.0, "max_val": 20.0},
            {"name": "20 - 30", "val": 25.0, "min_val": 20.0, "max_val": 30.0},
            {"name": "30 - 40", "val": 35.0, "min_val": 30.0, "max_val": 40.0},
            {"name": "40 - 50", "val": 45.0, "min_val": 40.0, "max_val": 50.0},
            {"name": "50 +", "val": 50.0, "min_val": 50.0, "max_val": None},
        ],
    },
]

GROUPS_OF_INTEREST = [
    "Conchs",
    "Corallivorous snails",
    "Crabs / Shrimps",
    "Crown-of-thorns starfish (COTS)",
    "Giant clams",
    "Lobsters",
    "Octopus",
    "Other invertebrates",
    "Pearl oysters",
    "Polychaete worms",
    "Sea cucumbers",
    "Sea urchins",
    "Triton's trumpets",
    "Trochus shells",
    "Turban shells",
]

HARVEST_TYPES = [
    "Dangerous / Venomous",
    "Food High Value Commercial",
    "Food Subsistence / Local Use",
    "Non-Harvest / Low Value",
    "Ornamental / Curio Trade",
    "Pest Species",
    "Protected / Conservation Value",
]

# Each entry: (phylum, class, order, family, genus, species, group_of_interest,
#              max_length, max_length_source, max_length_url, max_length_type,
#              harvest_type)
INVERT_SPECIES = [
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Conomurex",
        "luhuanus",
        "Conchs",
        8.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Conomurex-luhuanus.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Harpago",
        "arthriticus",
        "Conchs",
        22.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/14692_Harpago_arthriticus.htm",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Harpago",
        "chiragra",
        "Conchs",
        32.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Harpago-chiragra.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Lambis",
        "lambis",
        "Conchs",
        29.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Lambis-lambis.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Lambis",
        "millepeda",
        "Conchs",
        16.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Lambis-millepeda.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Lambis",
        "scorpius",
        "Conchs",
        20.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Lambis-scorpius.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda (conchs)",
        "Littorinimorpha",
        "Strombidae",
        "Lentigo",
        "lentiginosus",
        "Conchs",
        10.5,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Lentigo-lentiginosus.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Arthropoda",
        "Malacostraca (crabs / shrimps)",
        "Decapoda",
        "Inachidae",
        "Oncinopus",
        "angustifrons",
        "Crabs / Shrimps",
        8.0,
        "Reeflex - same as araneus species",
        "https://www.reeflex.net/tiere/10153_Oncinopus_araneus.htm",
        "carapace width",
        "Non-Harvest / Low Value",
    ),
    (
        "Arthropoda",
        "Malacostraca (crabs / shrimps)",
        "Decapoda",
        "Inachidae",
        "Oncinopus",
        "araneus",
        "Crabs / Shrimps",
        8.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/10153_Oncinopus_araneus.htm",
        "carapace width",
        "Non-Harvest / Low Value",
    ),
    (
        "Arthropoda",
        "Malacostraca (crabs / shrimps)",
        "Decapoda",
        "Inachidae",
        "Oncinopus",
        "neptunus",
        "Crabs / Shrimps",
        2.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/6192_Oncinopus_neptunus.htm",
        "carapace width",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Asteroidea (crown-of-thorns starfish - COTS)",
        "Valvatida",
        "Acanthasteridae",
        "Acanthaster",
        "planci",
        "Crown-of-thorns starfish (COTS)",
        80.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Acanthaster-planci.html",
        "arm length",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Coralliophila",
        "erosa",
        "Corallivorous snails",
        3.8,
        "Reeflex",
        "https://www.reeflex.net/tiere/15274_Coralliophila_erosa.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Coralliophila",
        "violacea",
        "Corallivorous snails",
        4.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/14038_Coralliophila_violacea.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Drupella",
        "cornus",
        "Corallivorous snails",
        4.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/15258_Drupella_cornus.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Drupella",
        "eburnea",
        "Corallivorous snails",
        4.0,
        "Reeflex - same as cornus species",
        "https://www.reeflex.net/tiere/15258_Drupella_cornus.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Drupella",
        "fragum",
        "Corallivorous snails",
        3.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/15259_Drupella_fragum.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Drupella",
        "margariticola",
        "Corallivorous snails",
        4.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/7527_Drupella_margariticola.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Mollusca",
        "Gastropoda (corallivorous snails)",
        "Neogastropoda",
        "Muricidae",
        "Drupella",
        "rugosa",
        "Corallivorous snails",
        4.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/15257_Drupella_rugosa.htm",
        "shell length/diameter",
        "Pest Species",
    ),
    (
        "Echinodermata",
        "Crinoidea",
        "Comatulida",
        "Colobometridae",
        "Colobometra",
        "perspinosa",
        "Other invertebrates",
        40.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/4832_Colobometra_perspinosa.htm",
        "arm length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Crinoidea",
        "Comatulida",
        "Comatulidae",
        "Comaster",
        "schlegelii",
        "Other invertebrates",
        35.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/4830_Comaster_schlegelii.htm",
        "arm length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Crinoidea",
        "Comatulida",
        "Comatulidae",
        "Davidaster",
        "rubiginosus",
        "Other invertebrates",
        25.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/7493_Davidaster_rubiginosus.htm",
        "arm length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Ophiuroidea",
        "Amphilepidida",
        "Ophiotrichidae",
        "Ophiothrix",
        "fragilis",
        "Other invertebrates",
        25.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/701_Ophiothrix_fragilis.htm",
        "arm length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Crinoidea",
        "Comatulida",
        "Comatulidae",
        "Anneissia",
        "bennetti",
        "Other invertebrates",
        35.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/4828_Anneissia_bennetti.htm",
        "arm length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Crinoidea",
        "Comatulida",
        "Tropiometridae",
        "Tropiometra",
        "afra",
        "Other invertebrates",
        44.0,
        "Reef Life Survey",
        "https://reeflifesurvey.com/species/tropiometra-afra/",
        "arm length",
        "Non-Harvest / Low Value",
    ),
    (
        "Mollusca",
        "Bivalvia (giant clams)",
        "Cardiida",
        "Cardiidae",
        "Hippopus",
        "hippopus",
        "Giant clams",
        50.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Hippopus-hippopus.html",
        "shell length",
        "Protected / Conservation Value",
    ),
    (
        "Mollusca",
        "Bivalvia (giant clams)",
        "Cardiida",
        "Cardiidae",
        "Tridacna",
        "crocea",
        "Giant clams",
        15.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Tridacna-crocea.html",
        "shell length",
        "Protected / Conservation Value",
    ),
    (
        "Mollusca",
        "Bivalvia (giant clams)",
        "Cardiida",
        "Cardiidae",
        "Tridacna",
        "maxima",
        "Giant clams",
        41.7,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Tridacna-maxima.html",
        "shell length",
        "Protected / Conservation Value",
    ),
    (
        "Mollusca",
        "Bivalvia (giant clams)",
        "Cardiida",
        "Cardiidae",
        "Tridacna",
        "squamosa",
        "Giant clams",
        45.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Tridacna-squamosa.html",
        "shell length",
        "Protected / Conservation Value",
    ),
    (
        "Arthropoda",
        "Malacostraca (lobsters)",
        "Decapoda",
        "Palinuridae",
        "Panulirus",
        "versicolor",
        "Lobsters",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Panulirus-versicolor.html",
        "carapace length",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Cephalopoda (octopus)",
        "Octopoda",
        "Octopodidae",
        "Octopus",
        "cyanea",
        "Octopus",
        22.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Octopus-cyanea.html",
        "mantle length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia",
        "Ostreida",
        "Gryphaeidae",
        "Hyotissa",
        "hyotis",
        "Other invertebrates",
        30.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Hyotissa-hyotis.html",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia",
        "Pectinida",
        "Pectinidae",
        "Pedum",
        "spondyloideum",
        "Other invertebrates",
        6.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/3416_Pedum_spondyloideum.htm",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia",
        "Venerida",
        "Veneridae",
        "Periglypta",
        "reticulata",
        "Other invertebrates",
        9.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Periglypta-reticulata.html",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia",
        "Pteriida",
        "Pinnidae",
        "Pinna",
        "bicolor",
        "Other invertebrates",
        50.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Pinna-bicolor.html",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia",
        "Pectinida",
        "Spondylidae",
        "Spondylus",
        "varius",
        "Other invertebrates",
        20.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/1014_Spondylus_varius.htm",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Cnidaria",
        "Hexacorallia",
        "Actiniaria",
        "Stichodactylidae",
        "Radianthus",
        "magnifica",
        "Other invertebrates",
        100.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/989_Radianthus_magnifica.htm",
        "pedal disc diameter",
        "Ornamental / Curio Trade",
    ),
    (
        "Mollusca",
        "Bivalvia (pearl oysters)",
        "Ostreida",
        "Margaritidae",
        "Pinctada",
        "imbricata",
        "Pearl oysters",
        8.8,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Pinctada-imbricata.html",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia (pearl oysters)",
        "Ostreida",
        "Margaritidae",
        "Pinctada",
        "margaritifera",
        "Pearl oysters",
        9.8,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Pinctada-margaritifera.html",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Bivalvia (pearl oysters)",
        "Ostreida",
        "Pteriidae",
        "Pteria",
        "penguin",
        "Pearl oysters",
        30.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Pteria-penguin.html",
        "shell length",
        "Food Subsistence / Local Use",
    ),
    (
        "Annelida",
        "Polychaeta (polychaete worms)",
        "Sabellida",
        "Sabellidae",
        "Anamobaea",
        "orstedii",
        "Polychaete worms",
        6.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/5386_Anamobaea_orstedii.htm",
        "body length",
        "Ornamental / Curio Trade",
    ),
    (
        "Annelida",
        "Polychaeta (polychaete worms)",
        "Sabellida",
        "Sabellidae",
        "Anamobaea",
        "phyllisae",
        "Polychaete worms",
        4.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/14338_Anamobaea_phyllisae.htm",
        "body length",
        "Ornamental / Curio Trade",
    ),
    (
        "Annelida",
        "Polychaeta (polychaete worms)",
        "Sabellida",
        "Sabellidae",
        "Bispira",
        "melanostigma",
        "Polychaete worms",
        6.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/6701_Bispira_melanostigma.htm",
        "body length",
        "Ornamental / Curio Trade",
    ),
    (
        "Annelida",
        "Polychaeta (polychaete worms)",
        "Sabellida",
        "Sabellidae",
        "Bispira",
        "brunnea",
        "Polychaete worms",
        6.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/2064_Bispira_brunnea.htm",
        "body length",
        "Ornamental / Curio Trade",
    ),
    (
        "Annelida",
        "Polychaeta (polychaete worms)",
        "Sabellida",
        "Sabellidae",
        "Sabellastarte",
        "spectabilis",
        "Polychaete worms",
        8.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/1035_Sabellastarte_spectabilis.htm",
        "body length",
        "Ornamental / Curio Trade",
    ),
    (
        "Annelida",
        "Polychaeta (polychaete worms)",
        "Sabellida",
        "Serpulidae",
        "Spirobranchus",
        "giganteus",
        "Polychaete worms",
        20.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Spirobranchus-giganteus.html",
        "body length",
        "Ornamental / Curio Trade",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Conidae",
        "Conus",
        "imperialis",
        "Other invertebrates",
        11.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Conus-imperialis.html",
        "shell length/diameter",
        "Dangerous / Venomous",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Conidae",
        "Conus",
        "radiatus",
        "Other invertebrates",
        10.9,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Conus-radiatus.html",
        "shell length/diameter",
        "Dangerous / Venomous",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Conidae",
        "Conus",
        "virgo",
        "Other invertebrates",
        15.1,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Conus-virgo.html",
        "shell length/diameter",
        "Dangerous / Venomous",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Littorinimorpha",
        "Cypraeidae",
        "Cribrarula",
        "cribraria",
        "Other invertebrates",
        4.4,
        "Reeflex",
        "https://www.reeflex.net/tiere/11205_Cribrarula_cribraria.htm",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Littorinimorpha",
        "Cypraeidae",
        "Cypraea",
        "tigris",
        "Other invertebrates",
        16.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Cypraea-tigris.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Littorinimorpha",
        "Littorinidae",
        "Littoraria",
        "scabra",
        "Other invertebrates",
        4.4,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Littoraria-scabra.html",
        "shell length/diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Muricidae",
        "Menathais",
        "tuberosa",
        "Other invertebrates",
        5.6,
        "Reeflex",
        "https://www.reeflex.net/tiere/7435_Menathais_tuberosa.htm",
        "shell length/diameter",
        "Non-Harvest / Low Value",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Muricidae",
        "Nassa",
        "serta",
        "Other invertebrates",
        7.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Nassa-serta.html",
        "shell length/diameter",
        "Non-Harvest / Low Value",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Terebridae",
        "Oxymeris",
        "maculata",
        "Other invertebrates",
        27.5,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Oxymeris-maculata.html",
        "shell length/diameter",
        "Dangerous / Venomous",
    ),
    (
        "Mollusca",
        "Gastropoda",
        "Neogastropoda",
        "Muricidae",
        "Tylothais",
        "aculeata",
        "Other invertebrates",
        6.0,
        "Australian museum",
        "https://lifg.australian.museum/Group.html?hierarchyId=PVWrQCLG&groupId=IlLfbcOO",
        "shell length/diameter",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Actinopyga",
        "echinites",
        "Sea cucumbers",
        36.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Actinopyga-echinites.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Actinopyga",
        "mauritiana",
        "Sea cucumbers",
        35.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Actinopyga-mauritiana.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Actinopyga",
        "miliaris",
        "Sea cucumbers",
        35.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Actinopyga-miliaris.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Bohadschia",
        "argus",
        "Sea cucumbers",
        60.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Bohadschia-argus.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Bohadschia",
        "marmorata",
        "Sea cucumbers",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Bohadschia-marmorata.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Bohadschia",
        "vitiensis",
        "Sea cucumbers",
        50.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Bohadschia-vitiensis.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Apodida",
        "Synaptidae",
        "Euapta",
        "godeffroyi",
        "Sea cucumbers",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Euapta-godeffroyi.html",
        "body length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Apodida",
        "Synaptidae",
        "Synapta",
        "maculata",
        "Sea cucumbers",
        200.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Synapta-maculata.html",
        "body length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "atra",
        "Sea cucumbers",
        60.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-atra.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "coluber",
        "Sea cucumbers",
        60.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-coluber.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "edulis",
        "Sea cucumbers",
        35.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-edulis.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "flavomaculata",
        "Sea cucumbers",
        55.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-flavomaculata.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "fuscogilva",
        "Sea cucumbers",
        57.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-fuscogilva.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "fuscopunctata",
        "Sea cucumbers",
        70.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-fuscopunctata.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "hilla",
        "Sea cucumbers",
        25.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-hilla.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "leucospilota",
        "Sea cucumbers",
        60.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-leucospilota.html",
        "body length",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "nobilis",
        "Sea cucumbers",
        60.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-nobilis.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "scabra",
        "Sea cucumbers",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-scabra.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Holothuria",
        "whitmaei",
        "Sea cucumbers",
        55.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Holothuria-whitmaei.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Holothuriida",
        "Holothuriidae",
        "Pearsonothuria",
        "graeffei",
        "Sea cucumbers",
        45.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Pearsonothuria-graeffei.html",
        "body length",
        "Non-Harvest / Low Value",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Synallactida",
        "Stichopodidae",
        "Stichopus",
        "chloronotus",
        "Sea cucumbers",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Stichopus-chloronotus.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Synallactida",
        "Stichopodidae",
        "Stichopus",
        "herrmanni",
        "Sea cucumbers",
        55.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Stichopus-herrmanni.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Synallactida",
        "Stichopodidae",
        "Stichopus",
        "horrens",
        "Sea cucumbers",
        90.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Stichopus-horrens.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Synallactida",
        "Stichopodidae",
        "Stichopus",
        "vastus",
        "Sea cucumbers",
        31.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Stichopus-vastus.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Synallactida",
        "Stichopodidae",
        "Thelenota",
        "ananas",
        "Sea cucumbers",
        80.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Thelenota-ananas.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Holothuroidea (sea cucumbers)",
        "Synallactida",
        "Stichopodidae",
        "Thelenota",
        "anax",
        "Sea cucumbers",
        100.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Thelenota-anax.html",
        "body length",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Diadematoida",
        "Diadematidae",
        "Diadema",
        "africanum",
        "Sea urchins",
        15.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/11231_Diadema_africanum.htm",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Diadematoida",
        "Diadematidae",
        "Diadema",
        "antillarum",
        "Sea urchins",
        20.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/6737_Diadema_antillarum.htm",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Diadematoida",
        "Diadematidae",
        "Diadema",
        "setosum",
        "Sea urchins",
        50.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/733_Diadema_setosum.htm",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Camarodonta",
        "Echinometridae",
        "Echinometra",
        "mathaei",
        "Sea urchins",
        8.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Echinometra-mathaei.html",
        "test diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Camarodonta",
        "Echinometridae",
        "Echinostrephus",
        "aciculatus",
        "Sea urchins",
        3.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/730_Echinostrephus_aciculatus.htm",
        "test diameter",
        "Food Subsistence / Local Use",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Diadematoida",
        "Diadematidae",
        "Echinothrix",
        "calamaris",
        "Sea urchins",
        15.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Echinothrix-calamaris.html",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Diadematoida",
        "Diadematidae",
        "Echinothrix",
        "diadema",
        "Sea urchins",
        20.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Echinothrix-diadema.html",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Camarodonta",
        "Echinometridae",
        "Heterocentrotus",
        "trigonarius",
        "Sea urchins",
        15.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/727_Heterocentrotus_trigonarius.htm",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Stomopneustoida",
        "Stomopneustidae",
        "Stomopneustes",
        "variolaris",
        "Sea urchins",
        11.0,
        "GBIF",
        "https://www.gbif.org/species/4341626",
        "test diameter",
        "Dangerous / Venomous",
    ),
    (
        "Echinodermata",
        "Echinoidea (sea urchins)",
        "Camarodonta",
        "Toxopneustidae",
        "Tripneustes",
        "gratilla",
        "Sea urchins",
        10.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Tripneustes-gratilla.html",
        "test diameter",
        "Food High Value Commercial",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Oreasteridae",
        "Culcita",
        "novaeguineae",
        "Other invertebrates",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Culcita-novaeguineae.html",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Oreasteridae",
        "Choriaster",
        "granulatus",
        "Other invertebrates",
        25.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/3184_Choriaster_granulatus.htm",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Goniasteridae",
        "Fromia",
        "indica",
        "Other invertebrates",
        10.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/715_Fromia_indica.htm",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Ophidiasteridae",
        "Linckia",
        "guildingi",
        "Other invertebrates",
        25.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/1316_Linckia_guildingi.htm",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Ophidiasteridae",
        "Linckia",
        "laevigata",
        "Other invertebrates",
        40.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Linckia-laevigata.html",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Ophidiasteridae",
        "Linckia",
        "multifora",
        "Other invertebrates",
        20.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/1736_Linckia_multifora.htm",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Echinodermata",
        "Asteroidea",
        "Valvatida",
        "Ophidiasteridae",
        "Nardoa",
        "novaecaledoniae",
        "Other invertebrates",
        25.0,
        "Reeflex",
        "https://www.reeflex.net/tiere/2741_Nardoa_novaecaledoniae.htm",
        "arm length",
        "Ornamental / Curio Trade",
    ),
    (
        "Mollusca",
        "Gastropoda (Triton's trumpets)",
        "Littorinimorpha",
        "Charoniidae",
        "Charonia",
        "tritonis",
        "Triton's trumpets",
        50.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Charonia-tritonis.html",
        "shell length/diameter",
        "Protected / Conservation Value",
    ),
    (
        "Mollusca",
        "Gastropoda (trochus shells)",
        "Trochida",
        "Tegulidae",
        "Rochia",
        "nilotica",
        "Trochus shells",
        15.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Rochia-nilotica.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Gastropoda (trochus shells)",
        "Trochida",
        "Tegulidae",
        "Tectus",
        "pyramis",
        "Trochus shells",
        15.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Tectus-pyramis.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Gastropoda (trochus shells)",
        "Trochida",
        "Trochidae",
        "Trochus",
        "maculatus",
        "Trochus shells",
        7.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Trochus-maculatus.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Gastropoda (turban shells)",
        "Trochida",
        "Turbinidae",
        "Turbo",
        "argyrostomus",
        "Turban shells",
        10.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Turbo-argyrostomus.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Gastropoda (turban shells)",
        "Trochida",
        "Turbinidae",
        "Turbo",
        "marmoratus",
        "Turban shells",
        22.0,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Turbo-marmoratus.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Gastropoda (turban shells)",
        "Trochida",
        "Turbinidae",
        "Turbo",
        "petholatus",
        "Turban shells",
        8.5,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Turbo-petholatus.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
    (
        "Mollusca",
        "Gastropoda (turban shells)",
        "Trochida",
        "Turbinidae",
        "Turbo",
        "setosus",
        "Turban shells",
        8.5,
        "SeaLifeBase – species",
        "https://www.sealifebase.se/summary/Turbo-setosus.html",
        "shell length/diameter",
        "Food High Value Commercial",
    ),
]

# The CSV row 20 has "Crinoidea " (trailing space) for Colobometra.
# Normalise to "Crinoidea" so it merges with the other Crinoidea rows.
INVERT_SPECIES = [
    (phylum, cls.strip(), order, family, genus, species, goi, ml, mls, mlu, mlt, ht)
    for (phylum, cls, order, family, genus, species, goi, ml, mls, mlu, mlt, ht) in INVERT_SPECIES
]


def seed_macroinvertebrate_data(apps, schema_editor):
    InvertBeltTransectWidth = apps.get_model("api", "InvertBeltTransectWidth")
    InvertSizeBin = apps.get_model("api", "InvertSizeBin")
    InvertSize = apps.get_model("api", "InvertSize")
    InvertGroupOfInterest = apps.get_model("api", "InvertGroupOfInterest")
    InvertHarvestType = apps.get_model("api", "InvertHarvestType")
    InvertPhylum = apps.get_model("api", "InvertPhylum")
    InvertClass = apps.get_model("api", "InvertClass")
    InvertOrder = apps.get_model("api", "InvertOrder")
    InvertFamily = apps.get_model("api", "InvertFamily")
    InvertGenus = apps.get_model("api", "InvertGenus")
    InvertSpecies = apps.get_model("api", "InvertSpecies")

    for w in INVERT_BELT_TRANSECT_WIDTHS:
        InvertBeltTransectWidth.objects.get_or_create(name=w["name"], defaults={"val": w["val"]})

    for bin_data in INVERT_SIZE_BINS:
        sb, _ = InvertSizeBin.objects.get_or_create(val=bin_data["val"])
        for size in bin_data["sizes"]:
            InvertSize.objects.get_or_create(
                invert_bin_size=sb,
                name=size["name"],
                defaults={
                    "val": size["val"],
                    "min_val": size["min_val"],
                    "max_val": size["max_val"],
                },
            )

    goi_map = {}
    for name in GROUPS_OF_INTEREST:
        goi_map[name], _ = InvertGroupOfInterest.objects.get_or_create(name=name)

    ht_map = {}
    for name in HARVEST_TYPES:
        ht_map[name], _ = InvertHarvestType.objects.get_or_create(name=name)

    phylum_map = {}
    class_map = {}
    order_map = {}
    family_map = {}
    genus_map = {}

    # Approval status: SUPERUSER_APPROVED = 90 from BaseAttributeModel
    APPROVED = 90

    for row in INVERT_SPECIES:
        (
            phylum_name,
            class_name,
            order_name,
            family_name,
            genus_name,
            species_name,
            goi_name,
            max_length,
            max_length_source,
            max_length_url,
            max_length_type,
            harvest_type_name,
        ) = row

        if phylum_name not in phylum_map:
            phylum_map[phylum_name], _ = InvertPhylum.objects.get_or_create(
                name=phylum_name, defaults={"status": APPROVED}
            )

        phylum = phylum_map[phylum_name]
        class_key = (phylum_name, class_name)
        if class_key not in class_map:
            class_map[class_key], _ = InvertClass.objects.get_or_create(
                name=class_name, phylum=phylum, defaults={"status": APPROVED}
            )

        invert_class = class_map[class_key]
        order_key = (phylum_name, class_name, order_name)
        if order_key not in order_map:
            order_map[order_key], _ = InvertOrder.objects.get_or_create(
                name=order_name, invert_class=invert_class, defaults={"status": APPROVED}
            )

        invert_order = order_map[order_key]
        family_key = (phylum_name, class_name, order_name, family_name)
        if family_key not in family_map:
            family_map[family_key], _ = InvertFamily.objects.get_or_create(
                name=family_name, order=invert_order, defaults={"status": APPROVED}
            )

        invert_family = family_map[family_key]
        genus_key = (phylum_name, class_name, order_name, family_name, genus_name)
        if genus_key not in genus_map:
            genus_map[genus_key], _ = InvertGenus.objects.get_or_create(
                name=genus_name, family=invert_family, defaults={"status": APPROVED}
            )

        invert_genus = genus_map[genus_key]
        InvertSpecies.objects.get_or_create(
            name=species_name,
            genus=invert_genus,
            defaults={
                "status": APPROVED,
                "max_length": max_length,
                "max_length_source": max_length_source,
                "max_length_url": max_length_url,
                "max_length_type": max_length_type,
                "group_of_interest": goi_map.get(goi_name),
                "harvest_type": ht_map.get(harvest_type_name),
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0106_macroinvertebrate_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invertspecies",
            name="max_length_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="size source URL"),
        ),
        migrations.RunPython(seed_macroinvertebrate_data, migrations.RunPython.noop),
    ]
