# Generated by Django 4.2.26 on 2026-05-06 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0110_macroinvertebrate_schema3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invertspecies",
            name="group_of_interest",
        ),
    ]
