# Generated by Django 4.2.26 on 2026-06-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0115_goi_schema_finalize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="benthic_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.benthicattribute"
            ),
        ),
    ]
