# Generated by Django 4.2.26 on 2026-05-30 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0116_gfcr_phase2"),
        ("api", "0116_remove_invert_harvest_type"),
    ]

    operations = []
