# Generated by Django 4.2.26 on 2026-06-02 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0117_merge_0116_annotation_benthic_attribute_protect_0116_remove_invert_harvest_type",
        ),
        ("api", "0117_merge_20260530_1302"),
    ]

    operations = []
