# Generated by Django 4.2.26 on 2026-06-10 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0119_beltinvertobssqlmodel_beltinvertsesqlmodel_and_more"),
        ("api", "0119_invert_attribute_revision_trigger"),
    ]

    operations = []
