# Generated by Django 4.2.26 on 2026-06-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0124_mv_invert_attributes_goi_family_order_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvertAttributeView",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("name_goi", models.CharField(blank=True, max_length=200, null=True)),
                ("name_class", models.CharField(blank=True, max_length=200, null=True)),
                ("name_order", models.CharField(blank=True, max_length=200, null=True)),
                ("name_family", models.CharField(blank=True, max_length=200, null=True)),
                ("name_genus", models.CharField(blank=True, max_length=200, null=True)),
                ("name_species", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "mv_invert_attributes",
                "managed": False,
            },
            bases=("api.invertattribute",),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="authuser",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="benthicattributegrowthform",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="covariate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="labelmapping",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="obsbenthicphotoquadrat",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="obsbenthicpit",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="observer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="obshabitatcomplexity",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="obsquadratbenthicpercent",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="summarycachequeue",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="benthicattributegrowthform",
            constraint=models.UniqueConstraint(
                fields=("benthic_attribute", "growth_form"),
                name="unique_benthicattributegrowthform_attribute_growthform",
            ),
        ),
        migrations.AddConstraint(
            model_name="covariate",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="unique_sitecovariate_site_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="labelmapping",
            constraint=models.UniqueConstraint(
                fields=("benthic_attribute", "growth_form", "provider", "provider_id"),
                name="unique_labelmapping_attribute_growthform_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="obsbenthicphotoquadrat",
            constraint=models.UniqueConstraint(
                fields=(
                    "benthic_photo_quadrat_transect",
                    "quadrat_number",
                    "attribute",
                    "growth_form",
                ),
                name="unique_obsbenthicphotoquadrat_pqt_quadrat_attribute_growthform",
            ),
        ),
        migrations.AddConstraint(
            model_name="obsbenthicpit",
            constraint=models.UniqueConstraint(
                fields=("benthicpit", "interval"), name="unique_obsbenthicpit_pit_interval"
            ),
        ),
        migrations.AddConstraint(
            model_name="observer",
            constraint=models.UniqueConstraint(
                fields=("transectmethod", "profile"), name="unique_observer_transectmethod_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="obshabitatcomplexity",
            constraint=models.UniqueConstraint(
                fields=("habitatcomplexity", "interval"),
                name="unique_obshabitatcomplexity_habitatcomplexity_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="obsquadratbenthicpercent",
            constraint=models.UniqueConstraint(
                fields=("bleachingquadratcollection", "quadrat_number"),
                name="unique_obsquadratbenthicpercent_collection_quadrat",
            ),
        ),
        migrations.AddConstraint(
            model_name="summarycachequeue",
            constraint=models.UniqueConstraint(
                fields=("project_id", "processing"),
                name="unique_summarycachequeue_project_processing",
            ),
        ),
    ]
