# Generated by Django 4.2.26 on 2026-06-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0125_remove_include_from_observation_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvertAttributeView",
            fields=[
                (
                    "invertattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.invertattribute",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("name_goi", models.CharField(blank=True, max_length=200, null=True)),
                ("name_class", models.CharField(blank=True, max_length=200, null=True)),
                ("name_order", models.CharField(blank=True, max_length=200, null=True)),
                ("name_family", models.CharField(blank=True, max_length=200, null=True)),
                ("name_genus", models.CharField(blank=True, max_length=200, null=True)),
                ("name_species", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "mv_invert_attributes",
                "managed": False,
            },
            bases=("api.invertattribute",),
        ),
    ]
