# Generated by Django 4.2.26 on 2026-06-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0127_refresh_mv_invert_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="benthicattribute",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
