# Generated by Django 4.2.26 on 2026-06-30 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0125_unique_together_to_unique_constraints"),
        ("api", "0127_refresh_mv_invert_attributes"),
    ]

    operations = []
