# Generated by Django 4.2.26 on 2026-07-01 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0128_benthicattribute_notes"),
        ("api", "0128_merge_20260630_1901"),
    ]

    operations = []
