# Generated by Django 4.2.26 on 2026-07-10 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0129_merge_20260701_1228"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="belttransectwidthcondition",
            options={"ordering": ("val",)},
        ),
    ]
