# Generated by Django 5.2.16 on 2026-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0130_alter_belttransectwidthcondition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarysampleeventmodel",
            name="depth_avg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="depth mean (m)"
            ),
        ),
        migrations.AddField(
            model_name="summarysampleeventmodel",
            name="depth_sd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="depth standard deviation (m)",
            ),
        ),
    ]
