# Generated by Django 5.2.16 on 2026-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0131_summarysampleeventmodel_depth_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beltinvertobsmodel",
            name="reef_slope",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="beltinvertsumodel",
            name="reef_slope",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
