# Generated by Django 5.2.16 on 2026-08-05 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0131_export_covariates"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Covariate",
        ),
    ]
