# Generated by Django 5.2.16 on 2026-08-17 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0130_gfcr_phase4"),
        ("api", "0132_add_reef_slope_to_belt_invert_obs_su"),
    ]

    operations = []
