# Generated by Django 5.2.16 on 2026-09-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_classifier_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beltfishobsmodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='beltfishsumodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='benthiclitobsmodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='benthiclitsumodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='benthicphotoquadrattransectobsmodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='benthicphotoquadrattransectsumodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='benthicpitobsmodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='benthicpitsumodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='habitatcomplexityobsmodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
        migrations.AlterField(
            model_name='habitatcomplexitysumodel',
            name='transect_len_surveyed',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='transect length surveyed (m)'),
        ),
    ]
