"""
Centralized cdk-nag suppressions for all stacks.

Each suppression documents the reason and whether the finding is:
  - ACCEPTED: The current configuration is intentional and appropriate.
  - TODO: Should be addressed in a future ticket.
"""

from aws_cdk import Stack
from cdk_nag import NagPackSuppression, NagSuppressions

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

ACCEPTED = "ACCEPTED"
TODO = "TODO"


def _suppress_stack(stack: Stack, suppressions: list[NagPackSuppression]) -> None:
    NagSuppressions.add_stack_suppressions(stack, suppressions)


# ---------------------------------------------------------------------------
# Per-stack suppression functions
# ---------------------------------------------------------------------------


def suppress_github_access(stack: Stack) -> None:
    _suppress_stack(
        stack,
        [
            NagPackSuppression(
                id="AwsSolutions-IAM4",
                reason=f"{TODO}: GithubAccessRole uses AdministratorAccess — "
                "scope down to specific CDK deployment permissions.",
                applies_to=[
                    "Policy::arn:<AWS::Partition>:iam::aws:policy/AdministratorAccess",
                ],
            ),
        ],
    )


def suppress_common(stack: Stack) -> None:
    _suppress_stack(
        stack,
        [
            # --- VPC ---
            NagPackSuppression(
                id="AwsSolutions-VPC7",
                reason=f"{TODO}: Enable VPC Flow Logs for network traffic auditing.",
            ),
            # --- Secrets Manager ---
            NagPackSuppression(
                id="AwsSolutions-SMG4",
                reason=f"{TODO}: Configure automatic rotation for DB credentials "
                "and report S3 user secret.",
            ),
            # --- RDS ---
            NagPackSuppression(
                id="AwsSolutions-RDS2",
                reason=f"{TODO}: Enable storage encryption on the RDS instance. "
                "May require a migration for the existing database.",
            ),
            NagPackSuppression(
                id="AwsSolutions-RDS3",
                reason=f"{TODO}: Evaluate multi-AZ for high availability. "
                "Currently single-AZ to manage costs.",
            ),
            NagPackSuppression(
                id="AwsSolutions-RDS11",
                reason=f"{ACCEPTED}: Port obfuscation provides minimal security "
                "benefit; the database is in a private isolated subnet.",
            ),
            # --- S3 ---
            NagPackSuppression(
                id="AwsSolutions-S1",
                reason=f"{TODO}: Enable server access logging on all S3 buckets.",
            ),
            NagPackSuppression(
                id="AwsSolutions-S10",
                reason=f"{TODO}: Add aws:SecureTransport condition to bucket policies.",
            ),
            # --- KMS ---
            NagPackSuppression(
                id="AwsSolutions-KMS5",
                reason=f"{TODO}: Enable automatic key rotation on the ECS exec KMS key.",
            ),
            # --- IAM wildcards (CDK-generated grants) ---
            NagPackSuppression(
                id="AwsSolutions-IAM5",
                reason=f"{ACCEPTED}: Wildcard permissions are generated by CDK "
                "grant helpers (e.g. bucket.grant_read_write) and are scoped "
                "to specific resource ARNs.",
            ),
            # --- ASG / EC2 ---
            NagPackSuppression(
                id="AwsSolutions-EC26",
                reason=f"{TODO}: Enable EBS encryption on the ASG launch template.",
            ),
            NagPackSuppression(
                id="AwsSolutions-AS3",
                reason=f"{TODO}: Configure SNS notifications for all ASG scaling events.",
            ),
            # --- Lambda (CDK-managed ASG drain hook) ---
            NagPackSuppression(
                id="AwsSolutions-IAM4",
                reason=f"{ACCEPTED}: AWSLambdaBasicExecutionRole is the standard "
                "managed policy for Lambda logging, generated by CDK.",
                applies_to=[
                    "Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
                ],
            ),
            NagPackSuppression(
                id="AwsSolutions-L1",
                reason=f"{ACCEPTED}: The drain-hook Lambda runtime is managed by "
                "the CDK ECS construct and auto-updated on CDK upgrades.",
            ),
            # --- SNS ---
            NagPackSuppression(
                id="AwsSolutions-SNS3",
                reason=f"{TODO}: Add aws:SecureTransport condition to SNS topic policies.",
            ),
            # --- ELB ---
            NagPackSuppression(
                id="AwsSolutions-ELB2",
                reason=f"{TODO}: Enable access logging on the Application Load Balancer.",
            ),
            # --- ALB Security Group ---
            NagPackSuppression(
                id="AwsSolutions-EC23",
                reason=f"{ACCEPTED}: The ALB is internet-facing and must allow "
                "inbound traffic from 0.0.0.0/0 on ports 80/443.",
            ),
        ],
    )


def suppress_static_site(stack: Stack) -> None:
    _suppress_stack(
        stack,
        [
            NagPackSuppression(
                id="AwsSolutions-S1",
                reason=f"{TODO}: Enable server access logging on the static site bucket.",
            ),
            NagPackSuppression(
                id="AwsSolutions-S10",
                reason=f"{TODO}: Add aws:SecureTransport condition to the bucket policy.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR1",
                reason=f"{ACCEPTED}: Geo restrictions are not required — "
                "MERMAID is a global marine-data platform.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR2",
                reason=f"{TODO}: Evaluate adding AWS WAF to the CloudFront distribution.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR3",
                reason=f"{TODO}: Enable CloudFront access logging.",
            ),
            NagPackSuppression(
                id="AwsSolutions-CFR7",
                reason=f"{TODO}: Migrate from Origin Access Identity (OAI) to "
                "Origin Access Control (OAC).",
            ),
        ],
    )


def suppress_api(stack: Stack) -> None:
    _suppress_stack(
        stack,
        [
            # --- IAM wildcards (CDK grants) ---
            NagPackSuppression(
                id="AwsSolutions-IAM5",
                reason=f"{ACCEPTED}: Wildcard permissions are generated by CDK "
                "grant helpers and are scoped to specific bucket/log-group ARNs.",
            ),
            # --- ECS env vars ---
            NagPackSuppression(
                id="AwsSolutions-ECS2",
                reason=f"{ACCEPTED}: Only non-sensitive configuration values "
                "(ENV_ID, BRANCH_NAME, queue URLs, etc.) are passed as "
                "environment variables. Secrets use Secrets Manager.",
            ),
            # --- SQS ---
            NagPackSuppression(
                id="AwsSolutions-SQS4",
                reason=f"{TODO}: Add aws:SecureTransport condition to SQS queue policies.",
            ),
            # --- SNS ---
            NagPackSuppression(
                id="AwsSolutions-SNS3",
                reason=f"{TODO}: Add aws:SecureTransport condition to SNS topic policies.",
            ),
        ],
    )


def suppress_sagemaker(stack: Stack) -> None:
    _suppress_stack(
        stack,
        [
            NagPackSuppression(
                id="AwsSolutions-IAM4",
                reason=f"{TODO}: Replace AmazonSageMakerFullAccess and "
                "SageMakerStudioFullAccess with scoped customer-managed policies.",
                applies_to=[
                    "Policy::arn:aws:iam::aws:policy/AmazonSageMakerFullAccess",
                    "Policy::arn:aws:iam::aws:policy/SageMakerStudioFullAccess",
                ],
            ),
            NagPackSuppression(
                id="AwsSolutions-IAM5",
                reason=f"{ACCEPTED}: Wildcard permissions are generated by CDK "
                "grant helpers and scoped to specific bucket ARNs. SageMaker "
                "and Glue wildcards are required for interactive notebook sessions.",
            ),
            NagPackSuppression(
                id="AwsSolutions-S1",
                reason=f"{TODO}: Enable server access logging on SageMaker S3 buckets.",
            ),
        ],
    )


# ---------------------------------------------------------------------------
# Main entry point — call from app.py after all stacks are created.
# ---------------------------------------------------------------------------


def apply_all(
    gh_access_stack: Stack,
    common_stack: Stack,
    dev_static_site_stack: Stack,
    prod_static_site_stack: Stack,
    dev_api_stack: Stack,
    prod_api_stack: Stack,
    dev_sagemaker_stack: Stack,
) -> None:
    suppress_github_access(gh_access_stack)
    suppress_common(common_stack)

    for static_stack in [dev_static_site_stack, prod_static_site_stack]:
        suppress_static_site(static_stack)

    for api_stack in [dev_api_stack, prod_api_stack]:
        suppress_api(api_stack)

    suppress_sagemaker(dev_sagemaker_stack)
