from .base import (
    FIELD_LEVEL,
    LIST_VALIDATION_TYPE,
    RECORD_LEVEL,
    ROW_LEVEL,
    VALUE_VALIDATION_TYPE,
    Validation,
)
from .validators import (
    AllEqualValidator,
    DepthValidator,
    DifferentInvertTransectWidthValidator,
    DifferentTransectLengthValidator,
    DrySubmitValidator,
    DuplicateValidator,
    InvertAllObsExcludedValidator,
    InvertCountValidator,
    InvertObsCountHighValidator,
    InvertSizeBinRequiredValidator,
    InvertSizeValidator,
    LenSurveyedValidator,
    ListRequiredValidator,
    ManagementRuleValidator,
    ObservationCountValidator,
    PositiveIntegerValidator,
    RequiredValidator,
    SampleDateValidator,
    SampleTimeValidator,
    SimilarDateSampleUnitsValidator,
    UniqueInvertBeltTransectValidator,
    UniqueManagementValidator,
    UniqueSiteValidator,
)

belt_invert_validations = [
    # ── Field level: required ────────────────────────────────────────────────
    Validation(
        validator=RequiredValidator(path="data.sample_event.site"),
        paths=["data.sample_event.site"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=RequiredValidator(path="data.sample_event.management"),
        paths=["data.sample_event.management"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=RequiredValidator(path="data.sample_event.sample_date"),
        paths=["data.sample_event.sample_date"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=RequiredValidator(path="data.beltinvert_transect.number"),
        paths=["data.beltinvert_transect.number"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=PositiveIntegerValidator(key_path="data.beltinvert_transect.number"),
        paths=["data.beltinvert_transect.number"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=RequiredValidator(path="data.beltinvert_transect.width"),
        paths=["data.beltinvert_transect.width"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=RequiredValidator(path="data.beltinvert_transect.len_surveyed"),
        paths=["data.beltinvert_transect.len_surveyed"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=RequiredValidator(path="data.beltinvert_transect.depth"),
        paths=["data.beltinvert_transect.depth"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # size_bin is nullable — no RequiredValidator
    Validation(
        validator=RequiredValidator(path="data.observers"),
        paths=["data.observers"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Field level: site / management validity ──────────────────────────────
    Validation(
        validator=UniqueSiteValidator(site_path="data.sample_event.site"),
        paths=["data.sample_event.site"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=UniqueManagementValidator(
            management_path="data.sample_event.management",
            site_path="data.sample_event.site",
        ),
        paths=["data.sample_event.management"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=ManagementRuleValidator(
            management_path="data.sample_event.management",
        ),
        paths=["data.sample_event.management"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Field level: numeric / format ────────────────────────────────────────
    Validation(
        validator=SampleDateValidator(
            sample_date_path="data.sample_event.sample_date",
            sample_time_path="data.beltinvert_transect.sample_time",
            site_path="data.sample_event.site",
        ),
        paths=["data.sample_event.sample_date"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=SampleTimeValidator(
            sample_time_path="data.beltinvert_transect.sample_time",
        ),
        paths=["data.beltinvert_transect.sample_time"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=LenSurveyedValidator(
            len_surveyed_path="data.beltinvert_transect.len_surveyed",
        ),
        paths=["data.beltinvert_transect.len_surveyed"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=DepthValidator(depth_path="data.beltinvert_transect.depth"),
        paths=["data.beltinvert_transect.depth"],
        validation_level=FIELD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Row level: required per observation ──────────────────────────────────
    Validation(
        validator=ListRequiredValidator(
            list_path="data.obs_belt_inverts",
            path="invert_attribute",
            name_prefix="invert_attribute",
            unique_identifier_label="observation_id",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=ROW_LEVEL,
        validation_type=LIST_VALIDATION_TYPE,
    ),
    Validation(
        validator=ListRequiredValidator(
            list_path="data.obs_belt_inverts",
            path="count",
            name_prefix="count",
            unique_identifier_label="observation_id",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=ROW_LEVEL,
        validation_type=LIST_VALIDATION_TYPE,
    ),
    Validation(
        validator=InvertSizeBinRequiredValidator(
            observations_path="data.obs_belt_inverts",
            size_path="size",
            size_bin_path="data.beltinvert_transect.size_bin",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=ROW_LEVEL,
        validation_type=LIST_VALIDATION_TYPE,
    ),
    # ── Row level: numeric / format ──────────────────────────────────────────
    Validation(
        validator=InvertCountValidator(
            observations_path="data.obs_belt_inverts",
            observation_count_path="count",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=ROW_LEVEL,
        validation_type=LIST_VALIDATION_TYPE,
    ),
    Validation(
        validator=InvertObsCountHighValidator(
            observations_path="data.obs_belt_inverts",
            observation_count_path="count",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=ROW_LEVEL,
        validation_type=LIST_VALIDATION_TYPE,
    ),
    Validation(
        validator=InvertSizeValidator(
            observations_path="data.obs_belt_inverts",
            observation_attribute_path="invert_attribute",
            observation_size_path="size",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=ROW_LEVEL,
        validation_type=LIST_VALIDATION_TYPE,
    ),
    # ── Record level: duplicate prevention ───────────────────────────────────
    Validation(
        validator=DuplicateValidator(
            list_path="data.obs_belt_inverts",
            key_paths=["invert_attribute", "size"],
            unique_identifier_label="observation_id",
        ),
        paths=["data.obs_belt_inverts"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=UniqueInvertBeltTransectValidator(
            protocol_path="data.protocol",
            label_path="data.beltinvert_transect.label",
            number_path="data.beltinvert_transect.number",
            width_path="data.beltinvert_transect.width",
            relative_depth_path="data.beltinvert_transect.relative_depth",
            site_path="data.sample_event.site",
            management_path="data.sample_event.management",
            sample_date_path="data.sample_event.sample_date",
            depth_path="data.beltinvert_transect.depth",
            observers_path="data.observers",
        ),
        paths=[
            "data.beltinvert_transect.label",
            "data.beltinvert_transect.number",
            "data.beltinvert_transect.width",
            "data.beltinvert_transect.relative_depth",
            "data.beltinvert_transect.depth",
            "data.sample_event.site",
            "data.sample_event.management",
            "data.sample_event.sample_date",
        ],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Record level: observation counts ─────────────────────────────────────
    Validation(
        validator=ObservationCountValidator(observations_path="data.obs_belt_inverts"),
        paths=["data.obs_belt_inverts"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=InvertAllObsExcludedValidator(observations_path="data.obs_belt_inverts"),
        paths=["data.obs_belt_inverts"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=AllEqualValidator(path="data.obs_belt_inverts", ignore_keys=["id"]),
        paths=["data.obs_belt_inverts"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Record level: similar date / management ──────────────────────────────
    Validation(
        validator=SimilarDateSampleUnitsValidator(
            protocol_path="data.protocol",
            site_path="data.sample_event.site",
            management_path="data.sample_event.management",
            sample_date_path="data.sample_event.sample_date",
        ),
        paths=["data.sample_event.sample_date"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Record level: cross-sample-event consistency ─────────────────────────
    Validation(
        validator=DifferentInvertTransectWidthValidator(
            site_path="data.sample_event.site",
            management_path="data.sample_event.management",
            sample_date_path="data.sample_event.sample_date",
            width_path="data.beltinvert_transect.width",
        ),
        paths=["data.beltinvert_transect.width"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    Validation(
        validator=DifferentTransectLengthValidator(
            protocol_path="data.protocol",
            site_path="data.sample_event.site",
            management_path="data.sample_event.management",
            sample_date_path="data.sample_event.sample_date",
            len_surveyed_path="data.beltinvert_transect.len_surveyed",
        ),
        paths=["data.beltinvert_transect.len_surveyed"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
    ),
    # ── Record level: dry submit (runs last, only if no errors) ─────────────
    Validation(
        validator=DrySubmitValidator(),
        paths=["__all__"],
        validation_level=RECORD_LEVEL,
        validation_type=VALUE_VALIDATION_TYPE,
        requires_instance=True,
        delay_validation=True,
    ),
]
