name: DeployCDKStacks

on:
  push:
    branches:
      - dev

env:
  CDK_VERSION: 2.29.1
  ENV: dev
  # PIPENV_VENV_IN_PROJECT: "true"

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3
      
      - name: Install CDK
        run: |
          iac/install_cdk.sh

      - name: CDK Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
          PYTHONPATH: ${{ github.workspace }}
          DEPLOY_AWS_ACCT: ${{ secrets.DEPLOY_AWS_ACCT }}
        run: |
          cd iac && cdk deploy --require-approval never ${ENV}-mermaid-api-django
