name: DeployCDKStacks

on:
  push:
    branches:
      - dev
      - 165-gh-actions
    tags:
      - 'v[0-9]+.[0-9]+'        # eg: v1.1
      - 'v[0-9]+.[0-9]+.[0-9]+' # eg: v1.1.1

      # The following tags allow you to deploy prod on the new AWS account only.
      # TODO: remove after migration
      - 'w[0-9]+.[0-9]+'        # eg: w1.1
      - 'w[0-9]+.[0-9]+.[0-9]+' # eg: w1.1.1

concurrency:
  group: api-deployment-${{ github.ref }}

jobs:
  call-test:
    uses: ./.github/workflows/_test.yml

  deploy:
    needs: [call-test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10"

      - uses: actions/checkout@v4.2.2

      - name: Install CDK
        run: |
          iac/install_cdk.sh

      - name: Set target and version for dev
        if: startsWith(github.ref, 'refs/heads/dev')
        run: |
          echo "TARGET=dev" >> "$GITHUB_ENV"
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "$short_sha" > src/VERSION.txt
          cat src/VERSION.txt

      - name: Set target and version for prod
        if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "TARGET=prod" >> "$GITHUB_ENV"
          echo "${{ github.ref_name }}" > src/VERSION.txt
          cat src/VERSION.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEPLOY_AWS_ACCT }}:role/${{ secrets.DEPLOY_AWS_ROLE }}
          aws-region: us-east-1
          role-skip-session-tagging: true
      - name: CDK Deploy
        env:
          DEPLOY_AWS_ROLE: ${{ secrets.DEPLOY_AWS_ROLE }}
          SYS_EMAIL: ${{ secrets.SYS_EMAIL }}
          PYTHONPATH: ${{ github.workspace }}
          DEPLOY_AWS_ACCT: ${{ secrets.DEPLOY_AWS_ACCT }}
        run: |
          cd iac && cdk deploy \
            --require-approval never \
            "${{ env.TARGET }}"-mermaid-api-django \
            "${{ env.TARGET }}"-mermaid-static-site \
            "mermaid-api-infra-common" \
            "GithubAccess"


