name: DeployCDKStacks

on:
  push:
    branches:
      - dev
    tags:
      - 'v[0-9]+.[0-9]+'        # eg: v1.1
      - 'v[0-9]+.[0-9]+.[0-9]+' # eg: v1.1.1

      # The following tags allow you to deploy prod on the new AWS account only.
      # TODO: remove after migration
      - 'w[0-9]+.[0-9]+'        # eg: w1.1
      - 'w[0-9]+.[0-9]+.[0-9]+' # eg: w1.1.1

concurrency:
  group: api-deployment-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  call-test:
    uses: ./.github/workflows/_test.yml

  deploy:
    needs: [call-test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: '22.11.0'

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12.0"

      - uses: actions/checkout@v4.2.2

      - name: Install CDK
        run: |
          iac/install_cdk.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          DEPLOY_AWS_ROLE: ${{ secrets.DEPLOY_AWS_ROLE }}
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CDK_DEFAULT_ACCOUNT }}:role/${{ secrets.DEPLOY_AWS_ROLE }}
          aws-region: us-east-1
          role-skip-session-tagging: true
      - name: CDK Deploy DEV
        if: startsWith(github.ref, 'refs/heads/dev')
        env:
          DEPLOY_AWS_ROLE: ${{ secrets.DEPLOY_AWS_ROLE }}
          SYS_EMAIL: ${{ secrets.SYS_EMAIL }}
          PYTHONPATH: ${{ github.workspace }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: us-east-1
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }}) && \
          echo "$short_sha" > src/VERSION.txt && \
          cat src/VERSION.txt && \
          cd iac && cdk deploy \
            --require-approval never \
            GithubAccess \
            mermaid-api-infra-common \
            dev-mermaid-api-django \
            dev-mermaid-static-site
      - name: CDK Deploy PROD
        if: startsWith(github.ref, 'refs/tags')
        env:
          DEPLOY_AWS_ROLE: ${{ secrets.DEPLOY_AWS_ROLE }}
          SYS_EMAIL: ${{ secrets.SYS_EMAIL }}
          PYTHONPATH: ${{ github.workspace }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: us-east-1
        run: |
          echo "${{ github.ref_name }}" > src/VERSION.txt && \
          cat src/VERSION.txt && \
          cd iac && cdk deploy \
            --require-approval never \
            GithubAccess \
            mermaid-api-infra-common \
            prod-mermaid-api-django \
            prod-mermaid-static-site



