name: DeployCDKStacks

on:
  push:
    branches:
      - dev
    tags:
      - 'w[0-9]+.[0-9]+'        # eg: v1.1
      - 'w[0-9]+.[0-9]+.[0-9]+' # eg: v1.1.1

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3
      
      - name: Install CDK
        run: |
          iac/install_cdk.sh

      - name: Set target for dev
        if: startsWith(github.ref, 'refs/heads/dev')
        run: |
          echo "TARGET=dev" >> "$GITHUB_ENV"
      
      - name: Set target for prod
        if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "TARGET=prod" >> "$GITHUB_ENV"
          
      - name: CDK Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
          PYTHONPATH: ${{ github.workspace }}
          DEPLOY_AWS_ACCT: ${{ secrets.DEPLOY_AWS_ACCT }}
        run: |
          cd iac && cdk deploy --require-approval never "${{ env.TARGET }}"-mermaid-api-django

      
