name: pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev

permissions:
  actions: write
  contents: read
  id-token: write

env:
  ENV: dev
  AWS_DEFAULT_REGION: us-east-1

jobs:

  call-test:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/_test.yml

  cdk-diff:
    # environment: dev
    needs: [call-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '^22.11.0'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "^3.12.0"

      - uses: actions/checkout@v3

      - name: Install CDK
        run: |
          cd iac && ./install_cdk.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          DEPLOY_AWS_ROLE: ${{ secrets.DEPLOY_AWS_ROLE }}
        with:
          role-to-assume: arn:aws:iam::${{ secrets.CDK_DEFAULT_ACCOUNT }}:role/${{ secrets.DEPLOY_AWS_ROLE }}
          aws-region: us-east-1
          role-skip-session-tagging: true

      - name: CDK Diff
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          PYTHONPATH: ${{ github.workspace }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          SYS_EMAIL: ${{ secrets.SYS_EMAIL }}
        run: |
          cd iac && ./cdk_diff.sh
