name: pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev

env:
  ENV: dev
  AWS_DEFAULT_REGION: us-east-1

jobs:

  call-test:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/_test.yml
   
  cdk-diff:
    # environment: dev
    # needs: [call-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3
      
      - name: Install CDK
        run: |
          cd iac && ./install_cdk.sh

      # - name: Cache CDK out
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       iac/cdk.out/
      #     key: cdk-out-dev-${{ steps.get-date.outputs.date }}
      #     restore-keys: |
      #       cdk-out-dev-
      
      - name: CDK Diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          PYTHONPATH: ${{ github.workspace }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
        run: |
          cd iac && ./cdk_diff.sh
