name: pr

on:
  pull_request:
    branches:
      - develop

env:
  CDK_VERSION: 2.29.1
  ENV: dev
  AWS_DEFAULT_REGION: us-east-1

jobs:
   
  cdk-diff:
    # environment: dev
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      
      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.10"
      
      # - name: Install CDK CLI
      #   run: |
      #     npm install -g aws-cdk@${CDK_VERSION}

      # Cache for current day
      # - name: Get Date
      #   id: get-date
      #   run: |
      #     echo "::set-output name=date::$(/bin/date -u "+%s")"
      #   shell: bash
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          debug_log: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
          # AWS_DEFAULT_REGION: 'us-east-1'

      
      # - name: Cache CDK out
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       iac/cdk.out/
      #     key: cdk-out-dev-${{ steps.get-date.outputs.date }}
      #     restore-keys: |
      #       cdk-out-dev-
      
      # - name: CDK Diff
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
      #   run: |
      #     cd iac && cdk deploy --require-approval never ${ENV}-*
